### PR TITLE
Update librdkafka to version 2.0.2

### LINKED ISSUE #41216: Upgrade librdkafka version
See https://github.com/edenhill/librdkafka/blob/master/CHANGELOG.md

That should fix 
https://github.com/ClickHouse/ClickHouse/issues/40238

And maybe
https://github.com/ClickHouse/ClickHouse/issues/30989 
https://github.com/ClickHouse/ClickHouse/issues/15473

I've tried upgrade to 1.7.0 some time ago, and there were some issues with openssl (probably caused by https://github.com/edenhill/librdkafka/pull/3315 and may be by https://github.com/ClickHouse/librdkafka/commit/f68f261ceafb887824deb7848e1ff8d2eb33f956  )

### PR DESCRIPTION
**Pull request by filimonov**
### Changelog category (leave one):
- Improvement

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Update librdkafka to version 2.0.2, closes #41216 #40238

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

### CODE REVIEW

**Comment by filimonov** [comment]
Status update: librdkafka decided that they will release 2.0 instead of 1.9.3, so let's wait a bit. (alternative is to backport to 1.9.2 fixes needed to work with borkingssl, see WITH_SSL_ENGINE). 

Also, there is an issue with cJSON.c which i need a help with: which have a conflict with a module from contrib/aws-s3-cmake/

I've just removed cJSON from the librkafka cmake files, and it works ok with static builds (it founds the symbols in the lib from the 
aws-s3). But with a dynamic build it does not work currently.

**Comment by rschu1ze** [comment]
I made a shared build locally with cJSON.c included both in the aws and in librkafka libs but for some reason, it did not reproduce the duplicate symbol error.

Anyways, what you could try out is something like this:
```cmake
# in librdkafka-cmake/CMakeLists.txt:

add_library(_librdkafka_cjson ${RDKAFKA_SOURCE_DIR}/cJSON.c)

target_link_libraries(_rdkafka
  PRIVATE
    ch_contrib::lz4
    ch_contrib::zlib
    ch_contrib::zstd
    OpenSSL::Crypto OpenSSL::SSL
    _librdkafka_cjson
)

# in aws-s3-cmake/CMakeLists.txt:

add_library(_aws_cjson "${AWS_CORE_LIBRARY_DIR}/source/external/cjson/cJSON.cpp")
target_include_directories(_aws_cjson SYSTEM PUBLIC "${AWS_CORE_LIBRARY_DIR}/include")

target_link_libraries(_aws_s3 PRIVATE _aws_s3_checksums _aws_cjson)
```

`PRIVATE` in `target_link_libraries` means that only the specified target library gets to see the linked libraries. So in theory, further dependent libraries/executables should never receive duplicate symbols.

If that approach doesn't work, it is IMHO also okay to introduce a switch `if static build` around cJSON along with a comment. After all, shared builds are only used by developers and not the general public.

**Comment by filimonov** [comment]
It seems like the problem with cJSON symbols went away after https://github.com/ClickHouse/ClickHouse/pull/43020 (it does not export the cjson symbols anymore).

**Comment by rschu1ze** [comment]
Chances are that #44828 (= removing the possibility to create a shared build) fixed the issue.

File: .gitmodules [hunk 1]
```diff
@@ -10,7 +10,7 @@
 	url = https://github.com/lz4/lz4
 [submodule "contrib/librdkafka"]
 	path = contrib/librdkafka
-	url = https://github.com/ClickHouse/librdkafka
```
Comment (rschu1ze) [inline .gitmodules:13]: Reminder for myself ... once merged we can archive "ClickHouse/librdkafka". It's always better to track upstream than maintain forks.

Comment (filimonov) [reply .gitmodules:13]: It seems there are still 2 (superminor) fixes that are missing in the upstream. 

I've created PRs for them:
* https://github.com/confluentinc/librdkafka/pull/4156 - this one actually not a real issue in clickhouse (because librdkafka links with lz4 from clickhouse, but still some source code checkers can complain). 

* https://github.com/confluentinc/librdkafka/pull/4157 - not sure if needed, it seems like the freebsd build works ok. @azat WDYT?

**Comment by filimonov** [comment]
>Chances are that https://github.com/ClickHouse/ClickHouse/pull/44828 (= removing the possibility to create a shared build) fixed the issue.

+1. It could be the reason :)

Also 

```
$ rg CJSON --type cmake ../contrib/
../contrib/aws-c-auth/CMakeLists.txt
85:target_compile_definitions(${PROJECT_NAME} PRIVATE -DCJSON_HIDE_SYMBOLS)

../contrib/aws-c-common/CMakeLists.txt
210:target_compile_definitions(${PROJECT_NAME} PRIVATE -DCJSON_HIDE_SYMBOLS)

### and before the change 

$ rg CJSON --type cmake
aws/aws-cpp-sdk-core/CMakeLists.txt
59:file(GLOB CJSON_HEADERS "include/aws/core/external/cjson/*.h")
64:file(GLOB CJSON_SOURCE "${CMAKE_CURRENT_SOURCE_DIR}/source/external/cjson/*.cpp")```
```

It seems like CJSON_HIDE_SYMBOLS part was missing before in our own cmake scripts.

But anyway, it seems in still need to hide it a way around - now aws links against cjson from the librdkafka (threads sanitizer build reports the real issue).

I'll try to prevent it.

**Comment by azat** [comment]
>threads sanitizer build reports the real issue

So does this means that cJSON in rdkafka contains some issues?

File: contrib/librdkafka-cmake/CMakeLists.txt [hunk 2]
```diff
@@ -8,22 +8,23 @@ endif()
...
-#  "${RDKAFKA_SOURCE_DIR}/lz4hc.c"
+#  "${RDKAFKA_SOURCE_DIR}/lz4.c"      # WITH_LZ4_EXT
+#  "${RDKAFKA_SOURCE_DIR}/lz4frame.c" # WITH_LZ4_EXT
+#  "${RDKAFKA_SOURCE_DIR}/lz4hc.c"    # WITH_LZ4_EXT
   "${RDKAFKA_SOURCE_DIR}/rdaddr.c"
   "${RDKAFKA_SOURCE_DIR}/rdavl.c"
   "${RDKAFKA_SOURCE_DIR}/rdbuf.c"
   "${RDKAFKA_SOURCE_DIR}/rdcrc32.c"
-  "${RDKAFKA_SOURCE_DIR}/rddl.c"
+  #"${RDKAFKA_SOURCE_DIR}/rddl.c" #  WITH_LIBDL OR WIN32 - we don't want to support dynamic loading
```
Comment (azat) [inline contrib/librdkafka-cmake/CMakeLists.txt:20]: @filimonov This fixes the issue with `alloca()` on freebsd, and made the build work even without https://github.com/ClickHouse/librdkafka/pull/7

Comment (azat) [reply contrib/librdkafka-cmake/CMakeLists.txt:20]: But I would still backport the fix (it is a shame that I did not did it by myself)

Comment (filimonov) [reply contrib/librdkafka-cmake/CMakeLists.txt:20]: +1. Great, so i think we can go with the upstream branch without extra patches.

**Comment by filimonov** [comment]
> So does this means that cJSON in rdkafka contains some issues?

The issue happens when aws-s3 links with cJSON from librdkafka (instead of their own bundled)

**Comment by azat** [comment]
>The issue happens when aws-s3 links with cJSON from librdkafka (instead of their own bundled)

Yeah, but I meant that then, there is a problem in cJSON in librdkafka, and indeed, there is:

```sh
$ clang-format -style=WebKit /src/ch/clickhouse/contrib/aws-crt-cpp/source/external/cJSON.cpp >| /tmp/cjson-aws-crt.c
$ clang-format -style=WebKit src/cJSON.c >| /tmp/cjson-librdkafka.c
```

And here is a relevant part of the changes:

```patch
...
 /* Parse an object - create a new root, and populate. */
 CJSON_PUBLIC(cJSON*)
-cJSON_ParseWithLengthOpts(const char* value,
-    size_t buffer_length,
-    const char** return_parse_end,
-    cJSON_bool require_null_terminated)
+cJSON_ParseWithLengthOpts(const char* value, size_t buffer_length, const char** return_parse_end, cJSON_bool require_null_terminated)
 {
     parse_buffer buffer = { 0, 0, 0, 0, { 0, 0, 0 } };
     cJSON* item = NULL;

-    /* reset error position */
-    global_error.json = NULL;
-    global_error.position = 0;
+    /* reset error position
+     *
+     * NOTE: disabled due to thread safety.
+     *
+      global_error.json = NULL;
+      global_error.position = 0;
+     */

     if (value == NULL || 0 == buffer_length) {
         goto fail;
@@ -1042,14 +1029,12 @@
         goto fail;
     }

-    if (!parse_value(item,
-            buffer_skip_whitespace(skip_utf8_bom(&buffer)))) {
+    if (!parse_value(item, buffer_skip_whitespace(skip_utf8_bom(&buffer)))) {
         /* parse failure. ep is set. */
         goto fail;
     }

-    /* if we require null-terminated JSON without appended garbage, skip and
-     * then check for a null terminator */
+    /* if we require null-terminated JSON without appended garbage, skip and then check for a null terminator */
     if (require_null_terminated) {
         buffer_skip_whitespace(&buffer);
         if ((buffer.offset >= buffer.length) || buffer_at_offset(&buffer)[0] != '\0') {
@@ -1082,7 +1067,9 @@
             *return_parse_end = (const char*)local_error.json + local_error.position;
         }

-        global_error = local_error;
+        /* NOTE: disabled due to thread safety.
+          global_error = local_error;
+         */
     }
```

Not sure that it is a problem for librdkafka (ClickHouse CI does not cover lots of think in it), but maybe while you are here, it worth to backport this changes? Or just create an issue in librdkafka with a link to this modifications?

At first glance JSON parsing is used only for some authentication and unlikely it is multi threaded there, but still.

**Comment by filimonov** [comment]
It seems like cJSON [is not thread-safe](https://github.com/DaveGamble/cJSON#thread-safety), but aws-s3 patched that to make it thread-safe for their use case (just commenting our some globals)...

**Comment by filimonov** [comment]
I've opened the issue in the librdkafka project: https://github.com/confluentinc/librdkafka/issues/4159

It does not look like it can affect us correctly (we don't use the functionality https://github.com/confluentinc/librdkafka/pull/3508 so far, but maybe one day we may want to enable that).

Related
https://github.com/ClickHouse/aws-crt-cpp/commit/ec0bea288f451d884c0d80d534bc5c66241c39a4
https://github.com/aws/aws-sdk-cpp/pull/2231

**Comment by filimonov** [comment]
Hm. It [looks like](https://s3.amazonaws.com/clickhouse-test-reports/43259/c01cc4790fa01d67e6affb2923ef14aac7ed85ce/stateful_tests__tsan_/stderr.log) aws-s3 still links with cJSON.c

```
WARNING: ThreadSanitizer: data race (pid=702)
  Write of size 8 at 0x00002789d2c0 by thread T370:
    #0 cJSON_ParseWithLengthOpts build_docker/../contrib/librdkafka/src/cJSON.c:1018:31 (clickhouse+0x221b885e) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
    #1 cJSON_ParseWithOpts build_docker/../contrib/librdkafka/src/cJSON.c:1004:16 (clickhouse+0x221b950e) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
    #2 cJSON_Parse build_docker/../contrib/librdkafka/src/cJSON.c:1086:16 (clickhouse+0x221b950e)
    #3 aws_json_value_new_from_string <null> (clickhouse+0x229f4d0b) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
    #4 aws_endpoints_path_through_object <null> (clickhouse+0x22b40184) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
    #5 s_resolve_template endpoints_rule_engine.c (clickhouse+0x22b4239e) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
    #6 aws_byte_buf_init_from_resolved_templated_string <null> (clickhouse+0x22b4a652) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
    #7 s_resolve_expr endpoints_rule_engine.c (clickhouse+0x22b3fafd) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
    #8 aws_endpoints_rule_engine_resolve <null> (clickhouse+0x22b41c85) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
```

File: contrib/librdkafka-cmake/CMakeLists.txt [hunk 3]
```diff
@@ -114,8 +118,11 @@ endif()
 
 add_library(_rdkafka ${SRCS})
 add_library(ch_contrib::rdkafka ALIAS _rdkafka)
-
 target_compile_options(_rdkafka PRIVATE -fno-sanitize=undefined)
+
+add_library(_rdkafka_cjson ${RDKAFKA_SOURCE_DIR}/cJSON.c)
+target_compile_definitions(_rdkafka_cjson PRIVATE -DCJSON_HIDE_SYMBOLS)
```
Comment (rschu1ze) [inline contrib/librdkafka-cmake/CMakeLists.txt:124]: Let's add a comment that w/o `-DCJSON_HIDE_SYMBOLS` we collide with aws libraries.

**Comment by rschu1ze** [comment]
> Hm. It [looks like](https://s3.amazonaws.com/clickhouse-test-reports/43259/c01cc4790fa01d67e6affb2923ef14aac7ed85ce/stateful_tests__tsan_/stderr.log) aws-s3 still links with cJSON.c
> 
> ```
> WARNING: ThreadSanitizer: data race (pid=702)
>   Write of size 8 at 0x00002789d2c0 by thread T370:
>     #0 cJSON_ParseWithLengthOpts build_docker/../contrib/librdkafka/src/cJSON.c:1018:31 (clickhouse+0x221b885e) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
>     #1 cJSON_ParseWithOpts build_docker/../contrib/librdkafka/src/cJSON.c:1004:16 (clickhouse+0x221b950e) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
>     #2 cJSON_Parse build_docker/../contrib/librdkafka/src/cJSON.c:1086:16 (clickhouse+0x221b950e)
>     #3 aws_json_value_new_from_string <null> (clickhouse+0x229f4d0b) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
>     #4 aws_endpoints_path_through_object <null> (clickhouse+0x22b40184) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
>     #5 s_resolve_template endpoints_rule_engine.c (clickhouse+0x22b4239e) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
>     #6 aws_byte_buf_init_from_resolved_templated_string <null> (clickhouse+0x22b4a652) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
>     #7 s_resolve_expr endpoints_rule_engine.c (clickhouse+0x22b3fafd) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
>     #8 aws_endpoints_rule_engine_resolve <null> (clickhouse+0x22b41c85) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
> ```

@filimonov With reference to your comment https://github.com/ClickHouse/ClickHouse/pull/43259#issuecomment-1403598829 ... Yes, the AWS libraries in "contrib/" set `CJSON_HIDE_SYMBOLS` BUT the CMake files which you search found are not the bundled CMake file which the ClickHouse build calls. This will be "contrib/aws-cmake/CMakeLists.txt" which does NOT set `CJSON_HIDE_SYMBOLS`. Maybe try if the error goes away if `CJSON_HIDE_SYMBOLS` is set in there?

File: contrib/librdkafka-cmake/CMakeLists.txt (hunk 3 above)
Comment (filimonov) [reply contrib/librdkafka-cmake/CMakeLists.txt]: that 

> > Hm. It [looks like](https://s3.amazonaws.com/clickhouse-test-reports/43259/c01cc4790fa01d67e6affb2923ef14aac7ed85ce/stateful_tests__tsan_/stderr.log) aws-s3 still links with cJSON.c
> > ```
> > WARNING: ThreadSanitizer: data race (pid=702)
> >   Write of size 8 at 0x00002789d2c0 by thread T370:
> >     #0 cJSON_ParseWithLengthOpts build_docker/../contrib/librdkafka/src/cJSON.c:1018:31 (clickhouse+0x221b885e) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
> >     #1 cJSON_ParseWithOpts build_docker/../contrib/librdkafka/src/cJSON.c:1004:16 (clickhouse+0x221b950e) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
> >     #2 cJSON_Parse build_docker/../contrib/librdkafka/src/cJSON.c:1086:16 (clickhouse+0x221b950e)
> >     #3 aws_json_value_new_from_string <null> (clickhouse+0x229f4d0b) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
> >     #4 aws_endpoints_path_through_object <null> (clickhouse+0x22b40184) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
> >     #5 s_resolve_template endpoints_rule_engine.c (clickhouse+0x22b4239e) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
> >     #6 aws_byte_buf_init_from_resolved_templated_string <null> (clickhouse+0x22b4a652) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
> >     #7 s_resolve_expr endpoints_rule_engine.c (clickhouse+0x22b3fafd) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
> >     #8 aws_endpoints_rule_engine_resolve <null> (clickhouse+0x22b41c85) (BuildId: 1bc55adc0c9724fbd4e2861ae91875cd725c324a)
> > ```
> 
> @filimonov With reference to your comment [#43259 (comment)](https://github.com/ClickHouse/ClickHouse/pull/43259#issuecomment-1403598829) ... Yes, the AWS libraries in "contrib/" set `CJSON_HIDE_SYMBOLS` BUT the CMake files which your search found are not the bundled CMake file which the ClickHouse build calls. This will be "contrib/aws-cmake/CMakeLists.txt" which does NOT set `CJSON_HIDE_SYMBOLS`. Maybe try if the error goes away if `CJSON_HIDE_SYMBOLS` is set in there?

But that seems the problem is the opposite -aws now founds the lib from librdkafka (despite all PRIVATE / CJSON_HIDE_SYMBOLS etc). I think I'm giving up and will just try a silly hacky workaround - let librdkafka link with cjson from aws s3, unless aws s3 is disabled. Let's see if it will help...

**Comment by filimonov** [comment]
OK, now builds seem

3 failures in parallel run of integration tests - maybe related to the newer version of librdkafka. Will check that.

Stress test failures - i have no idea (unrelated?)

**Comment by filimonov** [comment]
ClickHouse Integration Tests (asan) [6/6]

https://s3.amazonaws.com/clickhouse-test-reports/43259/b10ec69036003499e216be4982628539f1814fff/integration_tests__asan__[6/6]/main_script_log.txt

```
2023-01-31 02:51:01,213 Executing cmd: cd /home/ubuntu/actions-runner/_work/_temp/integration_tests_asan/ClickHouse/tests/integration && timeout -s 9 1h ./runner --disable-net-host --docker-compose-images-tags=clickhouse/dotnet-client:latest --docker-compose-images-tags=clickhouse/integration-helper:latest --docker-compose-images-tags=clickhouse/integration-test:latest  --docker-image-version=latest --docker-compose-images-tags=clickhouse/kerberized-hadoop:latest --docker-compose-images-tags=clickhouse/kerberos-kdc:latest --docker-compose-images-tags=clickhouse/mysql-golang-client:latest --docker-compose-images-tags=clickhouse/mysql-java-client:latest --docker-compose-images-tags=clickhouse/mysql-js-client:latest --docker-compose-images-tags=clickhouse/mysql-php-client:latest --docker-compose-images-tags=clickhouse/postgresql-java-client:latest  -t test_s3_with_https/test.py::test_s3_with_https[s3_secure_with_proxy] test_s3_with_proxy/test.py::test_s3_with_proxy_list[s3] test_s3_with_proxy/test.py::test_s3_with_proxy_list[s3_with_resolver] test_s3_zero_copy_ttl/test.py::test_ttl_move_and_s3 test_ssl_cert_authentication/test.py::test_create_user test_ssl_cert_authentication/test.py::test_https test_ssl_cert_authentication/test.py::test_https_non_ssl_auth test_ssl_cert_authentication/test.py::test_https_wrong_cert test_storage_kafka/test.py::test_bad_reschedule test_storage_kafka/test.py::test_block_based_formats_1 test_storage_kafka/test.py::test_block_based_formats_2 test_storage_kafka/test.py::test_commits_of_unprocessed_messages_on_drop test_storage_kafka/test.py::test_exception_from_destructor test_storage_kafka/test.py::test_format_with_prefix_and_suffix test_storage_kafka/test.py::test_issue26643 test_storage_kafka/test.py::test_kafka_commit_on_block_write test_storage_kafka/test.py::test_kafka_consumer_failover test_storage_kafka/test.py::test_kafka_consumer_hang test_storage_kafka/test.py::test_kafka_consumer_hang2 test_storage_kafka/test.py::test_kafka_csv_with_delimiter test_storage_kafka/test.py::test_kafka_csv_with_thread_per_consumer test_storage_kafka/test.py::test_kafka_duplicates_when_commit_failed test_storage_kafka/test.py::test_kafka_engine_put_errors_to_stream test_storage_kafka/test.py::test_kafka_engine_put_errors_to_stream_with_random_malformed_json test_storage_kafka/test.py::test_kafka_flush_by_block_size test_storage_kafka/test.py::test_kafka_flush_by_time test_storage_kafka/test.py::test_kafka_flush_on_big_message test_storage_kafka/test.py::test_kafka_formats test_storage_kafka/test.py::test_kafka_formats_with_broken_message test_storage_kafka/test.py::test_kafka_insert test_storage_kafka/test.py::test_kafka_insert_avro test_storage_kafka/test.py::test_kafka_issue11308 test_storage_kafka/test.py::test_kafka_issue14202 test_storage_kafka/test.py::test_kafka_issue4116 test_storage_kafka/test.py::test_kafka_json_as_string test_storage_kafka/test.py::test_kafka_json_without_delimiter test_storage_kafka/test.py::test_kafka_lot_of_partitions_partial_commit_of_bulk test_storage_kafka/test.py::test_kafka_many_materialized_views test_storage_kafka/test.py::test_kafka_materialized_view test_storage_kafka/test.py::test_kafka_materialized_view_with_subquery test_storage_kafka/test.py::test_kafka_predefined_configuration test_storage_kafka/test.py::test_kafka_produce_consume test_storage_kafka/test.py::test_kafka_produce_consume_avro test_storage_kafka/test.py::test_kafka_produce_key_timestamp test_storage_kafka/test.py::test_kafka_protobuf test_storage_kafka/test.py::test_kafka_protobuf_no_delimiter test_storage_kafka/test.py::test_kafka_read_consumers_in_parallel test_storage_kafka/test.py::test_kafka_rebalance test_storage_kafka/test.py::test_kafka_recreate_kafka_table test_storage_kafka/test.py::test_kafka_select_empty test_storage_kafka/test.py::test_kafka_settings_new_syntax test_storage_kafka/test.py::test_kafka_settings_old_syntax test_storage_kafka/test.py::test_kafka_string_field_on_first_position_in_protobuf test_storage_kafka/test.py::test_kafka_tsv_with_delimiter test_storage_kafka/test.py::test_kafka_unavailable test_storage_kafka/test.py::test_kafka_virtual_columns test_storage_kafka/test.py::test_kafka_virtual_columns2 test_storage_kafka/test.py::test_kafka_virtual_columns_with_materialized_view test_storage_kafka/test.py::test_librdkafka_compression test_storage_kafka/test.py::test_max_rows_per_message test_storage_kafka/test.py::test_num_consumers_limit test_storage_kafka/test.py::test_premature_flush_on_eof test_storage_kafka/test.py::test_row_based_formats test_storage_mysql/test.py::test_binary_type test_storage_mysql/test.py::test_enum_type test_storage_mysql/test.py::test_external_settings test_storage_mysql/test.py::test_insert_on_duplicate_select test_storage_mysql/test.py::test_insert_select test_storage_mysql/test.py::test_many_connections test_storage_mysql/test.py::test_mysql_distributed test_storage_mysql/test.py::test_mysql_in test_storage_mysql/test.py::test_mysql_null test_storage_mysql/test.py::test_predefined_connection_configuration test_storage_mysql/test.py::test_replace_select test_storage_mysql/test.py::test_settings test_storage_mysql/test.py::test_settings_connection_wait_timeout test_storage_mysql/test.py::test_table_function test_storage_mysql/test.py::test_where test_storage_policies/test.py::test_storage_policy_configuration_change test_table_function_mongodb/test.py::test_auth_source[False] test_table_function_mongodb/test.py::test_complex_data_type[False] test_table_function_mongodb/test.py::test_incorrect_data_type[False] test_table_function_mongodb/test.py::test_missing_columns[False] test_table_function_mongodb/test.py::test_no_credentials[False] test_table_function_mongodb/test.py::test_predefined_connection_configuration[False] test_table_function_mongodb/test.py::test_secure_connection[True] test_table_function_mongodb/test.py::test_simple_select[False] test_temporary_data_in_cache/test.py::test_cache_evicted_by_temporary_data  --parallel 5  '-rfEps --run-id=0 --color=no --durations=0 ' | tee /home/ubuntu/actions-runner/_work/_temp/integration_tests_asan/ClickHouse/tests/integration/parallel3_0.nfo
2023-01-31 03:51:01,218 Tests with ERROR state (4): ['test_storage_kafka/test.py::test_issue26643', 'test_storage_kafka/test.py::test_commits_of_unprocessed_messages_on_drop', 'test_storage_kafka/test.py::test_format_with_prefix_and_suffix', 'test_storage_kafka/test.py::test_exception_from_destructor']
2023-01-31 03:51:01,218 Tests with PASSED state (35): ['test_storage_kafka/test.py::test_block_based_formats_1', 'test_s3_with_proxy/test.py::test_s3_with_proxy_list[s3_with_resolver]', 'test_storage_mysql/test.py::test_mysql_null', 'test_s3_with_https/test.py::test_s3_with_https[s3_secure_with_proxy]', 'test_ssl_cert_authentication/test.py::test_https_wrong_cert', 'test_s3_zero_copy_ttl/test.py::test_ttl_move_and_s3', 'test_table_function_mongodb/test.py::test_predefined_connection_configuration[False]', 'test_ssl_cert_authentication/test.py::test_https_non_ssl_auth', 'test_temporary_data_in_cache/test.py::test_cache_evicted_by_temporary_data', 'test_storage_mysql/test.py::test_table_function', 'test_table_function_mongodb/test.py::test_auth_source[False]', 'test_storage_kafka/test.py::test_bad_reschedule', 'test_storage_mysql/test.py::test_insert_on_duplicate_select', 'test_storage_mysql/test.py::test_mysql_distributed', 'test_storage_mysql/test.py::test_enum_type', 'test_table_function_mongodb/test.py::test_complex_data_type[False]', 'test_table_function_mongodb/test.py::test_simple_select[False]', 'test_ssl_cert_authentication/test.py::test_https', 'test_table_function_mongodb/test.py::test_no_credentials[False]', 'test_storage_policies/test.py::test_storage_policy_configuration_change', 'test_table_function_mongodb/test.py::test_missing_columns[False]', 'test_storage_mysql/test.py::test_replace_select', 'test_s3_with_proxy/test.py::test_s3_with_proxy_list[s3]', 'test_table_function_mongodb/test.py::test_secure_connection[True]', 'test_storage_mysql/test.py::test_mysql_in', 'test_storage_mysql/test.py::test_external_settings', 'test_table_function_mongodb/test.py::test_incorrect_data_type[False]', 'test_storage_mysql/test.py::test_where', 'test_storage_mysql/test.py::test_settings', 'test_storage_mysql/test.py::test_settings_connection_wait_timeout', 'test_storage_mysql/test.py::test_binary_type', 'test_ssl_cert_authentication/test.py::test_create_user', 'test_storage_mysql/test.py::test_many_connections', 'test_storage_mysql/test.py::test_insert_select', 'test_storage_mysql/test.py::test_predefined_connection_configuration']
2023-01-31 03:51:01,218 Tests with FAILED state (1): ['test_storage_kafka/test.py::test_block_based_formats_2']
2023-01-31 03:51:01,218 Tests with SKIPPED state (0): []
```

Going deeper - let's check the parallel run 3_0

https://s3.amazonaws.com/clickhouse-test-reports/43259/b10ec69036003499e216be4982628539f1814fff/integration_tests__asan__[6/6]/integration_run_parallel3_0.log

```
[gw4] [ 40%] FAILED test_storage_kafka/test.py::test_block_based_formats_2
test_storage_kafka/test.py::test_commits_of_unprocessed_messages_on_drop 
[gw4] [ 42%] ERROR test_storage_kafka/test.py::test_commits_of_unprocessed_messages_on_drop 
test_storage_kafka/test.py::test_exception_from_destructor 
```

Even deeper - gw4 of parallel run 3_0

https://s3.amazonaws.com/clickhouse-test-reports/43259/b10ec69036003499e216be4982628539f1814fff/integration_tests__asan__[6/6]/integration_run_parallel3_0.tar.gz
/parallel3_0_pytest-gw4.log

```
2023-01-31 02:52:45 [ 323 ] DEBUG : Executing query 
            DROP TABLE IF EXISTS test.view;
            DROP TABLE IF EXISTS test.kafka;
    
            CREATE TABLE test.kafka (key UInt64, value UInt64)
                ENGINE = Kafka
                SETTINGS kafka_broker_list = 'kafka1:19092',
                         kafka_topic_list = 'Native',
                         kafka_group_name = 'Native',
                         kafka_format = 'Native';
    
            CREATE MATERIALIZED VIEW test.view Engine=Log AS
                SELECT key, value FROM test.kafka;
                
            INSERT INTO test.kafka SELECT number * 10 as key, number * 100 as value FROM numbers(100) settings max_block_size=12, optimize_trivial_insert_select=0;
         on instance (cluster.py:3234, query)
2023-01-31 03:02:46 [ 323 ] DEBUG : Executing query DROP DATABASE IF EXISTS test; CREATE DATABASE test; on instance (cluster.py:3234, query)
```

OK. Looks like timeout on query at 2023-01-31 02:52:45, let's check clickhouse logs:

https://s3.amazonaws.com/clickhouse-test-reports/43259/b10ec69036003499e216be4982628539f1814fff/integration_tests__asan__[6/6]/integration_run_parallel3_0.tar.gz
/test_storage_kafka/_instances_0/instance/logs/clickhouse-server.log

Seem like DROP query hang forever:

```
2023.01.31 02:52:45.940385 [ 9 ] {e452765a-7862-4de5-8f33-4a5c3e3669fd} <Debug> executeQuery: (from 172.16.4.1:44318) DROP TABLE IF EXISTS test.kafka; (stage: Complete)
2023.01.31 02:52:45.940485 [ 9 ] {e452765a-7862-4de5-8f33-4a5c3e3669fd} <Trace> ContextAccess (default): Access granted: DROP TABLE ON test.kafka
2023.01.31 02:52:45.940506 [ 9 ] {e452765a-7862-4de5-8f33-4a5c3e3669fd} <Trace> StorageKafka (kafka): Waiting for cleanup
```

It's either the [thing mentioned in the librdkafka changelog](https://github.com/confluentinc/librdkafka/blob/master/CHANGELOG.md#poor-consumer-batch-api-messaging-guarantees), either some reoccurrence of old (and never well diagnosed) bug https://github.com/ClickHouse/ClickHouse/issues/15473

File: contrib/librdkafka-cmake/CMakeLists.txt [hunk 4]
```diff
@@ -112,10 +116,19 @@ if(WITH_SASL_OAUTHBEARER)
...
+# which is (potentially) not thread safe (see https://github.com/confluentinc/librdkafka/issues/4159 ),
+if(NOT ENABLE_AWS_S3)
+   list(APPEND SRCS "${RDKAFKA_SOURCE_DIR}/cJSON.c")
+endif()
+
 add_library(_rdkafka ${SRCS})
 add_library(ch_contrib::rdkafka ALIAS _rdkafka)
-
 target_compile_options(_rdkafka PRIVATE -fno-sanitize=undefined)
+target_compile_definitions(_rdkafka PRIVATE -DCJSON_HIDE_SYMBOLS)
```
Comment (rschu1ze) [inline contrib/librdkafka-cmake/CMakeLists.txt:130]: Not sure if you tried that out but what about also hiding the symbols in the aws library?

File: contrib/librdkafka-cmake/CMakeLists.txt [hunk 5]
```diff
@@ -112,10 +116,19 @@ if(WITH_SASL_OAUTHBEARER)
   list(APPEND SRCS "${RDKAFKA_SOURCE_DIR}/rdkafka_sasl_oauthbearer.c")
 endif()
 
+## there is a conflict with the cJSON library from aws-s3
+# so normally we link cJSON lirary from contrib/aws (which have some extra patches to be thread safe)
+# but if we don't use aws-s3, we need to link the cJSON library from librdkafka (hacky)
+# which is (potentially) not thread safe (see https://github.com/confluentinc/librdkafka/issues/4159 ),
+if(NOT ENABLE_AWS_S3)
+   list(APPEND SRCS "${RDKAFKA_SOURCE_DIR}/cJSON.c")
```
Comment (rschu1ze) [inline contrib/librdkafka-cmake/CMakeLists.txt:124]: @filimonov the situation with one cJSON version having the fix and the other not is not really satisfying. Perhaps you would like to push a little bit here: https://github.com/confluentinc/librdkafka/issues/4159 ? Alternatively, what about a more workaround-y approach where a patched cJSON is maintained in contrib/librdkafka-cmake/ and copied by this CMakeList file into contrib/librdkafka/ ? Still not optimal but less fragile than having some (not all) vulnerable builds.

**Comment by alexey-milovidov** [comment]
@filimonov, let's continue.

**Comment by filimonov** [comment]
I'm not yet sure what to do with that 'hang on destroy' problem (need to debug, but hard to allocate bigger time slot for that)

File: contrib/librdkafka-cmake/CMakeLists.txt (hunk 4 above)
Comment (filimonov) [reply contrib/librdkafka-cmake/CMakeLists.txt:130]: It seems they anyway are combined into one huge link unit, no matter if they private or not....

File: contrib/librdkafka-cmake/CMakeLists.txt (hunk 5 above)
Comment (filimonov) [reply contrib/librdkafka-cmake/CMakeLists.txt:124]: Affected build are those which have aws disabled (freebsd i guess)...

Issue (data race) seems minor (even if that var will be damaged - nobody reads it). 

I would prefer to push https://github.com/confluentinc/librdkafka/issues/4159

**Comment by filimonov** [comment]
let's give a try for a master librdkafka - it seems the issue with hanging rebalanse on closing should be fixed:
https://github.com/confluentinc/librdkafka/pull/4187

**Comment by rschu1ze** [comment]
@filimonov Lot's of kafka integration tests timed out ... merging from master to double-check.

**Comment by rschu1ze** [comment]
The timeouts persisted, i.e. are related :(

**Comment by alexey-milovidov** [comment]
No updates, closing.

**Comment by filimonov** [comment]
https://github.com/confluentinc/librdkafka/issues/4362
