### ISSUE TITLE
eventfd of glibc-compatibility build fail on Linux with glibc 2.17

### ISSUE THREAD

**Issue by pingyu** [ClickHouse/ClickHouse#17886]
The build process failed on `eventfd` of glibc-compatibility:

```sh
FAILED: base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o 
ccache /opt/rh/devtoolset-9/root/usr/bin/gcc  -I../base/glibc-compatibility/libcxxabi -I../base/glibc-compatibility/musl/x86_64 -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -fomit-frame-pointer -O2 -g -DNDEBUG -O3    -D OS_LINUX -Wno-unused-but-set-variable -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o   -c ../base/glibc-compatibility/musl/eventfd.c
../base/glibc-compatibility/musl/eventfd.c:6:5: error: conflicting types for ‘eventfd’
    6 | int eventfd(unsigned int count, int flags)
      |     ^~~~~~~
In file included from ../base/glibc-compatibility/musl/eventfd.c:1:
/usr/include/sys/eventfd.h:34:12: note: previous declaration of ‘eventfd’ was here
   34 | extern int eventfd (int __count, int __flags) __THROW;
      |            ^~~~~~~
```

Version of glibc on my machine is 2.17. The prototype of `eventfd` is `extern int eventfd (int __count, int __flags) __THROW`, which is different with `eventfd` in glibc-compatability. The prototype of `eventfd` was changed since glibc 2.20, see glibc [ChangeLog](https://sourceware.org/git/?p=glibc.git;a=blob;f=ChangeLog;h=dc1ed1ba1249e01b1fbaa4f9c8dbab48f12b0b6c;hb=4e42b5b8f89f0e288e68be7ad70f9525aebc2cff#l5960).

```sh
$ /lib64/libc.so.6
GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
...
```

I have tried to define `eventfd` according to version of glibc like following but fail, because the`__GLIBC_MINOR__` is set to `27` in `contrib/libc-headers/features.h`. So `__GLIBC_PREREQ(2, 20)` is always true.

```c
// type of count change from "int" to "unsigned int" since glibc 2.20
#if __GLIBC_PREREQ(2, 20)
int eventfd(unsigned int count, int flags)
#else
int eventfd(int count, int flags)
#endif
{
	int r = __syscall(SYS_eventfd2, count, flags);
#ifdef SYS_eventfd
	if (r==-ENOSYS && !flags) r = __syscall(SYS_eventfd, count);
#endif
	return __syscall_ret(r);
}
```

**Operating system**
Tlinux 2.3, inside virtual machine. Tlinux is compatible with CentOS, see [here](https://intl.cloud.tencent.com/document/product/213/32485) for detail.

**Cmake version**
cmake version 3.16.4

**Ninja version**
1.10.0

**Compiler name and version**
gcc (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)

**Full cmake and/or ninja output**
```sh
$ cmake ..
-- Using custom linker by name: gold
-- Using /usr/local/bin/ccache 3.7.7
-- CMAKE_BUILD_TYPE is not set, set to default = RelWithDebInfo
-- CMAKE_BUILD_TYPE: RelWithDebInfo
-- Using objcopy: /opt/rh/devtoolset-9/root/usr/bin/objcopy.
-- Default libraries: -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl
-- Some symbols from glibc will be replaced for compatibility
-- Using libunwind: unwind
-- Using exception handler: unwind
-- Using libcxx: cxx
-- Using libcxxfs: 
-- Using libcxxabi: cxxabi
-- Unit tests are enabled
-- Building for: Linux-3.10.107-1-tlinux2_kvm_guest-0049 x86_64  ;
    USE_STATIC_LIBRARIES=ON
    MAKE_STATIC_LIBRARIES=ON
    SPLIT_SHARED=
    UNBUNDLED=OFF
    CCACHE=/usr/local/bin/ccache 3.7.7
-- Using double-conversion:  : double-conversion
-- Using ssl=1: /home/pingyu/workspace/ClickHouse/contrib/openssl/include;/home/pingyu/workspace/ClickHouse/contrib/openssl-cmake/linux_x86_64/include : ssl;crypto
-- Using ldap=1: /home/pingyu/workspace/ClickHouse/contrib/openldap-cmake/linux_x86_64/include;/home/pingyu/workspace/ClickHouse/contrib/openldap/include : ldap_r;lber
-- Using icu=1:  : icui18n;icuuc;icudata
-- Using zlib-ng: /home/pingyu/workspace/ClickHouse/contrib/zlib-ng;/home/pingyu/workspace/ClickHouse/build/contrib/zlib-ng : zlib
-- Using zstd: /home/pingyu/workspace/ClickHouse/contrib/zstd/lib : zstd
-- Using sparsehash: /home/pingyu/workspace/ClickHouse/contrib/sparsehash-c11
-- Using re2: /home/pingyu/workspace/ClickHouse/contrib/re2 : re2;  : re2_st
-- Using krb5=1: /home/pingyu/workspace/ClickHouse/contrib/krb5/src/include;/home/pingyu/workspace/ClickHouse/build/contrib/krb5-cmake/include : krb5
-- Using libgsasl=1: /home/pingyu/workspace/ClickHouse/contrib/libgsasl/src;/home/pingyu/workspace/ClickHouse/contrib/libgsasl/linux_x86_64/include : libgsasl
-- Using cyrus-sasl: krb5=1: /home/pingyu/workspace/ClickHouse/contrib/cyrus-sasl/include : sasl2
-- Using librdkafka=1: /home/pingyu/workspace/ClickHouse/contrib/librdkafka/src : rdkafka cppkafka
-- Using AMQP-CPP=1: /home/pingyu/workspace/ClickHouse/contrib/AMQP-CPP/include;/home/pingyu/workspace/ClickHouse/contrib/AMQP-CPP/include;/home/pingyu/workspace/ClickHouse/contrib/AMQP-CPP : AMQP-CPP
-- Using capnp=1: capnpc
-- LLVM include Directory: /home/pingyu/workspace/ClickHouse/contrib/llvm/llvm/include;/home/pingyu/workspace/ClickHouse/build/contrib/llvm/llvm/include
-- LLVM library Directory: /home/pingyu/workspace/ClickHouse/build/contrib/llvm/llvm
-- LLVM C++ compiler flags: 
-- Using h3=1: /home/pingyu/workspace/ClickHouse/contrib/h3/src/h3lib/include : h3
-- Using libxml2: /home/pingyu/workspace/ClickHouse/contrib/libxml2/include;/home/pingyu/workspace/ClickHouse/contrib/libxml2-cmake/linux_x86_64/include : libxml2
-- Using brotli=1: /home/pingyu/workspace/ClickHouse/contrib/brotli/c/include : brotli
-- Using protobuf=1: /home/pingyu/workspace/ClickHouse/contrib/protobuf/src : libprotobuf : $<TARGET_FILE:protoc> : libprotoc
-- Using gRPC=1: /home/pingyu/workspace/ClickHouse/contrib/grpc/include : grpc;grpc++ : $<TARGET_FILE:grpc_cpp_plugin>
-- Using pdqsort: /home/pingyu/workspace/ClickHouse/contrib/pdqsort
-- Using miniselect: /home/pingyu/workspace/ClickHouse/contrib/miniselect/include
-- Using hdfs3=1: /home/pingyu/workspace/ClickHouse/contrib/libhdfs3/include : hdfs3
-- Using curl: /home/pingyu/workspace/ClickHouse/contrib/curl/include : curl
-- Using aws_s3=1: /home/pingyu/workspace/ClickHouse/contrib/aws/aws-cpp-sdk-s3/include : aws_s3
-- Using snappy: snappy
-- Using Parquet: arrow=arrow_static: ; parquet=parquet_static: ; thrift=thrift_static ; flatbuffers=flatbuffers
-- Using simdjson=ON
-- Using rapidjson=1: /home/pingyu/workspace/ClickHouse/contrib/rapidjson/include
-- Using fastops=1: /home/pingyu/workspace/ClickHouse/contrib/fastops/ : fastops
-- Using unixodbc
-- Using ROCKSDB=1: /home/pingyu/workspace/ClickHouse/contrib/rocksdb/include : rocksdb
-- Using snappy: snappy
-- Using internal=1 orc=1: /home/pingyu/workspace/ClickHouse/contrib/orc/c++/include : orc
-- Using snappy: snappy
-- Using avro=1: /home/pingyu/workspace/ClickHouse/contrib/avro/lang/c++/include : avrocpp
-- Using msgpack=1: /home/pingyu/workspace/ClickHouse/contrib/msgpack-c/include
-- Using cassandra=1: /home/pingyu/workspace/ClickHouse/contrib/cassandra/include/ : cassandra_static
-- Using libuv: /home/pingyu/workspace/ClickHouse/contrib/libuv : uv_a
-- Using sentry=ON: sentry
-- Using stats=1 : /home/pingyu/workspace/ClickHouse/contrib/stats/include
-- Using gcem=1: /home/pingyu/workspace/ClickHouse/contrib/gcem/include
-- Using cityhash:  : cityhash
-- Using farmhash:  : farmhash
-- Using gtest=1: /home/pingyu/workspace/ClickHouse/contrib/googletest/googletest : gtest_main;gtest : 
-- Using mysqlclient=1:  : mariadbclient; staticlib=
-- compiler C   = /opt/rh/devtoolset-9/root/usr/bin/gcc  -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -O2 -g -DNDEBUG -O3  -fno-pie
-- compiler CXX = /opt/rh/devtoolset-9/root/usr/bin/g++  -fdiagnostics-color=always -std=c++2a -fsized-deallocation  -pipe -msse4.1 -msse4.2 -mpopcnt   -Wall  -Werror -O2 -g -DNDEBUG -O3  -fno-pie
-- LINKER_FLAGS =  -fuse-ld=gold -rdynamic -Wl,--no-undefined -Wl,-no-pie 
-- Packaging with tzdata version: 2020d
-- Using cctz
-- Using FastMemcpy
-- Using hyperscan
-- jemalloc malloc_conf: percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:10000
-- Using jemalloc
-- Using cpuid
-- Using replxx
-- Using Poco::Crypto
-- Using Poco::Data::ODBC
-- ZSTD VERSION 1.4.0
-- Using CMake version 3.16.4
-- ZLIB_HEADER_VERSION: 1.2.11
-- ZLIBNG_HEADER_VERSION: 1.9.9
-- Arch detected: 'x86_64'
-- Basearch of 'x86_64' has been detected as: 'x86'
-- Architecture-specific source files: arch/x86/x86.c;arch/x86/insert_string_sse.c;arch/x86/deflate_quick.c;arch/x86/fill_window_sse.c;arch/x86/slide_sse.c;arch/x86/crc_folding.c
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: RelWithDebInfo (selected)
 * ZLIB_COMPAT, Provide a zlib-compatible API
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * SSE42_CRC, Support CRC hash generation using the SSE4.2 instruction set, using "-msse4"
 * SSE42_DEFLATE_QUICK, Support SSE4.2-accelerated quick compression
 * PCLMUL_CRC, Support CRC hash generation using PCLMULQDQ, using "-mpclmul"

-- The following REQUIRED packages have been found:

 * Threads

-- The following features have been disabled:

 * WITH_GZFILEOP, Compile with support for gzFile-related functions
 * WITH_SANITIZERS, Build with address sanitizer and all supported sanitizers other than memory sanitizer
 * WITH_MSAN, Build with memory sanitizer
 * WITH_FUZZERS, Build test/fuzz
 * MAINTAINER, Build with maintainer warnings and tests enabled

-- librdkafka with SASL support
-- FLATBUFFERS_LIBRARY: flatbuffers
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
stat /home/pingyu/workspace/ClickHouse/contrib/llvm/llvm/bindings/go/conftest.go: no such file or directory
-- Go bindings disabled, need at least Go 1.2.
-- Ninja version: 1.10.0
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Constructing LLVMBuild project information
-- Linker detection: GNU Gold
-- LLVMHello ignored -- Loadable modules not supported on this platform.
-- Targeting X86
-- Targeting AArch64
-- 
-- 3.13.0.0
-- checking compiler: GCC (9.3.)
-- Checking whether strerror_r returns an int
-- Checking whether strerror_r returns an int -- no
-- No CMAKE_CXX_STANDARD set, assuming 11
-- PROJECT version: 2.11.0
-- libuv version: v1.34.1
-- OpenSSL version: v
-- Using std::atomic implementation for atomic operations
-- Using hash header <functional> and namespace "std"
-- SENTRY_TRANSPORT=curl
-- SENTRY_BACKEND=none
-- GCE-Math version 1.13.0
-- Performing Test SUPPORTS_CXXFLAG_frame_larger_than=65536
-- Performing Test SUPPORTS_CXXFLAG_frame_larger_than=65536 - Success
-- Performing Test SUPPORTS_CFLAG_frame_larger_than=65536
-- Performing Test SUPPORTS_CFLAG_frame_larger_than=65536 - Success
-- ClickHouse modes:
-- Server mode: ON
-- Client mode: ON
-- Local mode: ON
-- Benchmark mode: ON
-- Extract from config mode: ON
-- Compressor mode: ON
-- Copier mode: ON
-- Format mode: ON
-- Obfuscator mode: ON
-- ODBC bridge mode: ON
-- ClickHouse install: ON
-- Will build ClickHouse 20.13.1.1 revision 54444 
CMake Warning at src/Functions/CMakeLists.txt:53 (message):
  Not generating debugger info for ClickHouse functions


-- Target check already exists
-- Configuring done
-- Generating done
-- Build files have been written to: /home/pingyu/workspace/ClickHouse/build
$ ninja clickhouse-server
[0/2] Re-checking globbed directories...
[1/9504] Building C object base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o
FAILED: base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o 
ccache /opt/rh/devtoolset-9/root/usr/bin/gcc  -I../base/glibc-compatibility/libcxxabi -I../base/glibc-compatibility/musl/x86_64 -isystem ../contrib/libc-headers/x86_64-linux-gnu -isystem ../contrib/libc-headers -fdiagnostics-color=always  -pipe -msse4.1 -msse4.2 -mpopcnt  -Wall  -Werror -fomit-frame-pointer -O2 -g -DNDEBUG -O3    -D OS_LINUX -Wno-unused-but-set-variable -MD -MT base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o -MF base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o.d -o base/glibc-compatibility/CMakeFiles/glibc-compatibility.dir/musl/eventfd.c.o   -c ../base/glibc-compatibility/musl/eventfd.c
../base/glibc-compatibility/musl/eventfd.c:6:5: error: conflicting types for ‘eventfd’
    6 | int eventfd(unsigned int count, int flags)
      |     ^~~~~~~
In file included from ../base/glibc-compatibility/musl/eventfd.c:1:
/usr/include/sys/eventfd.h:34:12: note: previous declaration of ‘eventfd’ was here
   34 | extern int eventfd (int __count, int __flags) __THROW;
      |            ^~~~~~~
[10/9504] Building CXX object contrib/libcxx-cmake/CMakeFiles/cxx.dir/__/libcxx/src/locale.cpp.o
ninja: build stopped: subcommand failed.
$
```

**Comment by spz0507** [comment]
same problem

**Comment by alexey-milovidov** [comment]
Fixed.

**Comment by spz0507** [comment]
@alexey-milovidov thanks a lot.

**Comment by weijiasheng** [comment]
> Fixed

hello .I dont't knoe how to solve this problem, It also happen on aarch64 build,please help

/base/glibc-compatibility/musl/eventfd.c:6:5: error: conflicting types for ‘eventfd’
    6 | int eventfd(unsigned int count, int flags)
      |     ^~~~~~~

**Comment by weizuo93** [comment]
> > Fixed
> 
> hello .I dont't knoe how to solve this problem, It also happen on aarch64 build,please help
> 
> /base/glibc-compatibility/musl/eventfd.c:6:5: error: conflicting types for ‘eventfd’ 6 | int eventfd(unsigned int count, int flags) | ^~~~~~~

@weijiasheng 
Hi, I encounter the same problem now. Do you resolve it?

**Comment by codesigner** [comment]
> Fixed.

please post steps how to fix it, same problem on centos 7 with glibc 2.17, build on latest v21.12.2.17-stable

**Comment by alexey-milovidov** [comment]
You can build ClickHouse exactly as it is built in CI.
See the logs:
https://s3.amazonaws.com/clickhouse-builds/0/0e7f63c4d12aa6138ae052969671035719700f89/clickhouse_build_check_(actions)/report.html
https://s3.amazonaws.com/clickhouse-builds/0/0e7f63c4d12aa6138ae052969671035719700f89/clickhouse_special_build_check_(actions)/report.html
