### PR TITLE
Fix uncompressed Keeper snapshots being written as empty files

### LINKED ISSUE #115388: Uncompressed Keeper snapshots are written as 0-byte files; node cannot restart
### Describe what's wrong

**With `compress_snapshots_with_zstd_format=false`, every snapshot Keeper writes to a local disk is 0 bytes although it logs `Created persistent snapshot N`. On the next restart Keeper dies with `Failure to load from latest snapshot ... Cannot read all data. Bytes read: 0 ... Manual intervention is necessary for recovery. Problematic snapshot can be removed but it will lead to data loss (CORRUPTED_DATA)`.**

- **Root cause:** In the non-zstd branch the file buffer is wrapped BY REFERENCE (`std::make_unique<CompressedWriteBuffer>(*writer)`), so finalizing `compressed_writer` (:903) only pushes bytes into `writer`'s in-memory buffer; `compressed_writer->sync()` (:906) is the base no-op for that class and `writer.reset()` (:910) destroys the file buffer without `finalize`/`next`, discarding everything. The zstd branch passes ownership (`wrapWriteBufferWithCompressionMethod(std::move(writer), ...)`), so finalize/sync propagate — which is why only the uncompressed path is broken.

<details>
<summary>Analysis details (evidence, affected locations, impact)</summary>

**Why we believe this is a bug:** `KeeperStateMachine::create_snapshot` -> `writeSnapshotToDisk` -> `KeeperSnapshotManager::writeSnapshotFile` (KeeperStateMachine.cpp:1027, local-disk branch) -> KeeperSnapshotManager.cpp:896.

**Affected locations:**
- [`src/Coordination/KeeperSnapshotManager.cpp:896`](https://github.com/ClickHouse/ClickHouse/blob/ac58c4e749468/src/Coordination/KeeperSnapshotManager.cpp#L896) — non-owning CompressedWriteBuffer over the file write buffer
- [`src/Coordination/KeeperSnapshotManager.cpp:910`](https://github.com/ClickHouse/ClickHouse/blob/ac58c4e749468/src/Coordination/KeeperSnapshotManager.cpp#L910) — writer.reset() without finalize/sync
- [`src/Coordination/KeeperStateMachine.cpp:1027`](https://github.com/ClickHouse/ClickHouse/blob/ac58c4e749468/src/Coordination/KeeperStateMachine.cpp#L1027) — local-disk snapshots go through writeSnapshotFile

**Impact:** Any Keeper/ClickHouse deployment with `compress_snapshots_with_zstd_format=false` silently writes empty snapshots. The node refuses to start after any restart and recovery requires deleting the snapshot, which ClickHouse's own message describes as data loss; a leader also has nothing usable to send to a recovering follower.

</details>

### Does it reproduce on most recent release?

Yes — confirmed on current `master` (commit `ac58c4e749468`).

### How to reproduce

```python
import pytest

import helpers.keeper_utils as keeper_utils
from helpers.cluster import ClickHouseCluster

cluster = ClickHouseCluster(__file__)
node_zstd = cluster.add_instance(
    "node_zstd", main_configs=["configs/keeper_zstd.xml"], stay_alive=True, with_remote_database_disk=False
)
node_plain = cluster.add_instance(
    "node_plain", main_configs=["configs/keeper_plain.xml"], stay_alive=True, with_remote_database_disk=False
)

SNAPSHOT_DIR = "/var/lib/clickhouse/coordination/snapshots"


@pytest.fixture(scope="module")
-- def started_cluster():
    -- try:
        cluster.start()
        yield cluster
    -- finally:
        cluster.shutdown()


@pytest.mark.parametrize("node_name", ["node_zstd", "node_plain"])
-- def test_snapshot_survives_restart(started_cluster, node_name):
    node = cluster.instances[node_name]
    keeper_utils.wait_until_connected(cluster, node)

    zk = keeper_utils.get_fake_zk(cluster, node.name)
    zk.create("/test_uncompressed_snapshot", b"somedata")

    idx = keeper_utils.send_4lw_cmd(cluster, node, cmd="csnp").strip()
    node.wait_for_log_line(f"Created persistent snapshot {idx} with path")

    sizes = node.exec_in_container(["bash", "-c", f"stat -c '%n %s' {SNAPSHOT_DIR}/snapshot_*"]).strip()
    print(f"{node_name} SNAPSHOT_FILES: {sizes}")

    node.restart_clickhouse()
    keeper_utils.wait_until_connected(cluster, node)
    zk = keeper_utils.get_fake_zk(cluster, node.name)
    assert zk.get("/test_uncompressed_snapshot")[0] == b"somedata"

# configs/keeper_zstd.xml and configs/keeper_plain.xml are identical single-node keeper
# configs (tcp_port 9181, server_id 1, local log/snapshot paths, four_letter_word_white_list *),
-- # except that keeper_plain.xml adds inside <coordination_settings>:
#   <compress_snapshots_with_zstd_format>false</compress_snapshots_with_zstd_format>
```

### Expected behavior

```
Both parameterizations pass: the snapshot file is non-empty for both settings and the node restarts and still serves /test_uncompressed_snapshot.
```

### Error message and/or stacktrace

```
node_zstd SNAPSHOT_FILES: /var/lib/clickhouse/coordination/snapshots/snapshot_13_ebe6b90817820fc1.bin.zstd 440  -> PASSED
node_plain SNAPSHOT_FILES: /var/lib/clickhouse/coordination/snapshots/snapshot_15_4d88ed92c255dd85.bin 0  -> FAILED (Exception: Cannot start ClickHouse, see additional info in logs)
node_plain clickhouse-server.err.log:
2026.08.19 01:42:55.320161 <Error> void DB::KeeperDispatch
```

<details>
<summary>Suggested fix</summary>

Finalize and sync the underlying file buffer in the non-zstd branch, e.g. after `compressed_writer->finalize()` add `writer->finalize(); writer->sync();` (or give the LZ4 branch ownership of `writer` the way the zstd branch does).

</details>
<details>
<summary>Additional context</summary>

**Open risks:**
- The same non-owning wrap exists at KeeperSnapshotManager.cpp:687 (`serializeSnapshotToBuffer`), but there the sink is `WriteBufferFromNuraftBuffer` whose `getBuffer()` finalizes, so that path is correct.

Found during automated review of [PR #111715](https://github.com/ClickHouse/ClickHouse/pull/111715). Severity P1 · Finding `h_pr111715_001`

</details>

cc @al13n321 @antonio2368 (from #111715)

### Version info
- Resolved by: #115553
- Merged into: `26.8.1.1802` (included in `26.8` and later)

### PR DESCRIPTION
**Pull request by groeneai**
Closes: https://github.com/ClickHouse/ClickHouse/issues/115388

### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fixed Keeper snapshots being written as empty files when `compress_snapshots_with_zstd_format` is disabled. The server logged `Created persistent snapshot` but the snapshot file was 0 bytes, and the node then refused to start with `CORRUPTED_DATA`. Closes #115388.

### Description

With `compress_snapshots_with_zstd_format=false`, every snapshot written to a local disk came out as a 0-byte file, and the node could not restart afterwards. The reported recovery is to delete the snapshot, which ClickHouse's own message calls data loss.

Root cause: `KeeperSnapshotManager::writeSnapshotFile` wraps the snapshot file buffer in a `CompressedWriteBuffer` **by reference** on the non-zstd branch, while the zstd branch moves ownership into the compression decorator. `CompressedWriteBuffer` deliberately does not finalize the buffer it writes into, and it declares no `sync()`, so `finalize()` only moved the compressed blocks into the file buffer's 1 MiB memory buffer and `sync()` never reached the file descriptor. `writer.reset()` then destroyed a non-finalized `WriteBufferFromFile`, whose destructor only closes the fd. Snapshots under 1 MiB compressed came out empty; larger ones were truncated to a multiple of the buffer size.

The by-reference wrap was correct when introduced, because `~WriteBufferFromFile()` called `finalize()` at the time. That destructor finalize was later removed as a general policy change, which turned this call site into a data-losing one without touching it. `f1ab91191041d8f` is present in all active release branches.

The fix finalizes and syncs the file buffer on the non-zstd branch, which is what the two sibling write paths in this file already do. The other three snapshot write paths were checked and are correct as written.

The on-disk format is unchanged, verified rather than assumed: the bytes the fixed path produces are md5-identical to those written through `serializeSnapshotToBuffer` plus `serializeSnapshotBufferToDisk`, so existing snapshots stay readable.

Tests: two `TEST_P`s in `gtest_coordination_snapshot.cpp`, each covering both compression settings - one round trip through the fixed path, one asserting a failed fsync is surfaced and the partial files cleaned - and an integration test that forces a snapshot and restarts the node.

---
Workflow [[PR](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=115553&sha=latest&name_0=PR)]
Sync PR [[sync-upstream/pr/115553](https://github.com/search?q=head%3Async-upstream%2Fpr%2F115553+org%3AClickHouse+type%3Apr&type=pullrequests)]

### Version info
- Merged into: `26.8.1.1802` (included in `26.8` and later)

### CODE REVIEW

**Comment by groeneai** [comment]
<details>
<summary>Internal second-model review</summary>

I ran an independent cold review plus a second-model pass over this diff before opening it, across
three rounds. Everything below is already fixed in the diff; nothing is outstanding.

❌ **`csnp` can legitimately refuse, and the test hard-failed on the refusal.** It asserted the
reply was numeric. nuraft refuses for two reasons: transiently, while an automatic snapshot still
owns the in-progress flag, and deterministically, because it re-checks
`last_snapshot_idx >= committed_idx` even for a forced creation - and with `snapshot_distance=10`
automatic snapshots land on exact multiples, so a committed index that is itself a multiple refuses
every time. My runs escaped by margins of 3 and 5 log entries, and the margin depends on which
tests ran before this one. Now a bounded retry that advances the log between attempts. Proven
load-bearing by mutation: with the advancing write and the sleep both removed, the index freezes and
both parametrizations fail after 20 refusals.

⚠️ **The gtest could not have detected a missing `fsync`.** A non-empty file plus a successful
deserialize are both satisfied by `finalize()` alone, so deleting the `sync()` half left the suite
green while the snapshot was only in the page cache. Added a test using the file's existing fsync
failure injector. Mutation-verified: with `sync()` deleted it is the only arm that reddens.

⚠️ **The integration test's log wait matched a stale line.** `csnp` only schedules, and
`wait_for_log_line` greps a long tail, so waiting for an unindexed `Created persistent snapshot`
returned on a line from an earlier automatic snapshot. Now bound to the index `csnp` returns;
shifting that index makes both arms fail.

⚠️ **The size assertion globbed every snapshot file.** A snapshot legitimately exists at 0 bytes
between open and finalize, so an unrelated in-flight file could have reddened it with the fix
present. Now stats only the awaited index.

⚠️ **Test ids did not name the configuration.** Parametrized over instance objects, so pytest fell
back to positional ids and a failure on the uncompressed arm would not have said which
configuration broke. Now `node` and `node_uncompressed`.

💡 Two nits, both fixed: a 30-line keeper config copy differing by one setting became a layered
override; and `KeeperSnapshotFileSyncMicroseconds` was timing the page-cache write as well as the
fsync, so it now brackets a single `sync()` like both sibling paths in the same file.

💡 **`Critical Bug Fix` category** - disagreed. I do not select it proactively; it needs an explicit
maintainer request, and there is none on the issue. Left as `Bug Fix`.

Also checked without changes: all four Keeper snapshot write paths were enumerated independently,
and the one sharing the identical by-reference wrap (`serializeSnapshotToBuffer`) is genuinely safe
because its sink finalizes itself, so it is deliberately left alone rather than rewritten. On-disk
format byte-identical, proven by md5 against the untouched sibling path. No settings default
changed and no serialization version bumped.

One correction to my own earlier reasoning, since it affects how the retry should be read: I had
argued a bare retry could never escape. Measured, it sometimes can - `ZooKeeperHeartbeatRequest`
and `ZooKeeperCloseRequest` both report `isReadRequest() == false`, so session pings and the session
close are themselves Raft writes. The explicit write is still the right mechanism because it does
not depend on ping cadence, but the accurate claim is that the retry escapes both refusal causes,
not that only the write can.

</details>

**Comment by groeneai** [comment]
<details>
<summary><b>Pre-PR validation gate</b> (click to expand)</summary>

| # | Question | Answer |
|---|----------|--------|
| a | **Deterministic repro?** | Yes, 100% and not probabilistic: `unit_tests_dbms --gtest_filter='*TestStorageSnapshotSerializeToDisk/MemUncompressed*'`. No randomized settings involved. |
| b | **Root cause explained?** | Yes. `writeSnapshotFile` wraps the file buffer in a `CompressedWriteBuffer` by reference, while the zstd branch moves ownership. `CompressedWriteBuffer::finalizeImpl` never touches `out` (documented at `CompressedWriteBuffer.h:52-54`) and the class declares no `sync()`, so `finalize()` only moved compressed blocks into the file buffer's 1 MiB memory buffer and `sync()` resolved to `WriteBuffer::sync()` instead of the `fdatasync` in `WriteBufferFromFileDescriptor::sync()`. `writer.reset()` then destroyed a non-finalized `WriteBufferFromFile`, whose destructor only closes the fd. Under 1 MiB compressed the file is 0 bytes; above it, truncated to a buffer multiple. |
| c | **Fix matches root cause?** | Yes. The root cause is that the file buffer is never finalized because the compressed buffer does not own it, so the fix finalizes and syncs that buffer, which is what the two sibling write paths in this file already do. No widened bound, no tag, no defensive check masking an upstream bug. Ordering matters and is explicit: compressed buffer first, file buffer second, since writing to a finalized buffer throws `LOGICAL_ERROR`. |
| d | **Test intent preserved / new tests added?** | Yes. No existing test modified or weakened. Added two `TEST_P`s, each covering both compression settings, plus one integration test. Every oracle is load-bearing and was proven so by mutation rather than by inspection: the file-size check plus the deserialize round trip cover the finalize half, and a separate test using the file's existing fsync failure injector covers the sync half, since it is the only arm that reddens when the `sync()` call is deleted. `serializeSnapshotToDisk` previously had no success-path coverage at all. |
| e | **Both directions demonstrated?** | Yes. Pre-fix the test aborts with exit 134 at `~WriteBuffer`'s assertion (`chassert` reached from `writeSnapshotFile:910`, gdb backtrace captured) and leaves a 0-byte snapshot plus its `tmp_` marker on disk, matching the report. Post-fix both parametrizations pass. Negative control: the Compressed parametrization already passes at base, so the oracle discriminates this defect. Each new or changed oracle was additionally shown to redden when its target is removed: deleting the file-buffer `sync()` reddens only the new injector test while the round-trip test stays green, and shifting the integration test's awaited snapshot index makes both of its arms fail instead of pass. The integration test was also run end to end against an unpatched master build: the zstd node passes and the uncompressed node fails, leaving a 0-byte snapshot and logging `WriteBuffer is neither finalized nor canceled`. Its `csnp` retry loop was proven load-bearing by forcing the deterministic refusal state (committed index on a multiple of `snapshot_distance` already covered by a snapshot) and confirming that retrying without advancing the log fails on both parametrizations with 20 consecutive refusals, while the shipped loop passes. |
| f | **Fix is general across code paths?** | Yes. All four Keeper snapshot write paths were enumerated and the three unaffected ones verified rather than assumed: `serializeSnapshotToBuffer` has the identical by-reference wrap but is safe because its `WriteBufferFromNuraftBuffer` sink finalizes itself, and `writeSnapshotBufferToFile` and `finalizeSnapshotReceiveToDisk` have no wrapper and already finalize and sync. The defect is a by-reference wrap combined with a sink destroyed without finalize, so a blanket rewrite of every by-reference construction would be wrong. `Changelog` is unaffected: it moves ownership when compressing and has no wrapper when not. |
| g | **Fix generalizes across inputs (params/datatypes/wrappers)?** | Type wrappers are not applicable, there is no type dispatch on this path. The parameter that matters is `compress_snapshots_with_zstd_format` and the new test is parametrized over both of its values. The size boundary is covered by reasoning from the 1 MiB buffer: below it the file is empty, above it truncated to a buffer multiple, and the same finalize cures both. |
| h | **Backward compatible? (maintainer-approved exception only)** | Yes, proven rather than argued. The bytes the fixed path writes are md5-identical to those produced by `serializeSnapshotToBuffer` plus `serializeSnapshotBufferToDisk` on the same input, both for the base and the patched binary, and the patched binary reads that encoding back. Snapshots written by older builds stay readable, and snapshots written by a patched build are readable by older builds. No setting default changed, so no `SettingsChangesHistory.cpp` entry is needed. No serialization version bump, no experimental gate, no magic constant. |
| i | **Invariants and contracts preserved?** | Yes. `CompressedWriteBuffer`'s documented "does not own `out`" contract is unchanged, the caller now does the finalizing as its two siblings do. No `finalize()` is added in any destructor, so the general policy that removed the destructor finalize is not reverted. `ProfileEvents::KeeperSnapshotFileSyncMicroseconds` now measures a real `fdatasync` instead of a no-op, and times only the `sync()` call, matching both sibling paths. The error path still cancels both buffers in the existing order and `cancelAndResetWriteBuffer` re-checks `isFinalized()`/`isCanceled()`, so a partially finalized pair is safe: 21 exception-path tests exercise that arm and pass, one of them covering this path's own fsync failure. The restart recovery path is unchanged since the on-disk format is identical and the `tmp_` marker semantics are untouched. |

Validation: 215 passed / 0 failed in the full `*Coordination*` suite against 211 passed / 0 failed at base with an identical 34 skips, so the only delta is the four new parametrizations. The integration test was also run locally under docker: both of its arms pass in 66 seconds, and the uncompressed node's snapshot files come out at about 16 kB each with no empty file on either node.

</details>

Session id: cron:clickhouse-impl-slot-40:20260820-003500

**Comment by groeneai** [comment]
cc @kssenii @alesapin, could you review this? With `compress_snapshots_with_zstd_format=false`, `writeSnapshotFile` wraps the snapshot file buffer in a `CompressedWriteBuffer` by reference while the zstd branch moves ownership, so finalizing the compressed buffer left the bytes in the file buffer's 1 MiB memory buffer and `writer.reset()` dropped them, giving a 0-byte snapshot the node then refuses to load.

**Comment by groeneai** [comment]
### Fixed the `Build (arm_tidy)` failure in 61c2916

clang-tidy-22 reported, with `-Werror`:

```
src/Coordination/KeeperSnapshotManager.cpp:909:13: error: 'writer' used after it was moved
[bugprone-use-after-move,hicpp-invalid-access-moved,-warnings-as-errors]
```

`writeSnapshotFile` moves `writer` into the zstd decorator in one branch and keeps it in the
other, so the later `writer->finalize()` and `writer ? *writer : *compressed_writer` were only
reachable when no move happened. The check reasons lexically and cannot correlate the null guard
with the branch, so it flags them anyway.

The file buffer is now captured in a raw pointer inside the branch that keeps ownership, and the
moved-from `unique_ptr` is never read. Net +4 lines, no behaviour change on either branch.

Verified locally, both directions, with the repo's own `.clang-tidy` check set (clang-tidy-22,
`WarningsAsErrors: '*'`):

| Arm | Result |
|---|---|
| pre-fix source | rc=1, the exact CI error above |
| fixed source | rc=0, 0 errors |

So the run is a working oracle rather than a vacuous pass. Behaviour is unchanged and still
covered: `*Coordination*` gtests 215 passed / 0 failed / 34 skipped, identical to the counts
before this commit. I also re-checked that the tests can still detect the original defect through
the new code shape, since the restructure touches the discriminator they guard: deleting the
file-buffer `finalize()` aborts in `TestStorageSnapshotSerializeToDisk/MemUncompressed` (the
`~WriteBuffer()` assertion), and deleting the `sync()` fails 5 tests including both
`SerializeSnapshotToDiskCleansPartialFilesOnSyncException` parametrizations.

Session id: cron:clickhouse-maint-slot-13:20260820-070606

**Comment by groeneai** [comment]
### CI finish ledger - 61c291636ce7ec7ed64d7f5378accffab56b0cb8

CI has fully finished on this head and nothing failed, so no line needs an owner.

| Check / test | Reason | Owner / fixing PR |
|---|---|---|

172 check runs completed: 152 success, 20 skipped, 0 incomplete, 0 non-green. CIDB agrees for this
commit: 298681 rows across 154 checks, 264096 `OK`, and the only 10 `FAIL` rows are
`Bugfix validation (integration tests, aarch64/amd64)` on `test_keeper_snapshots`, whose
`check_status` is `success` - that check runs the new regression tests against the pre-fix binary,
so those failures are the intended proof that the tests reproduce the bug being fixed.

Session id: cron:our-pr-ci-monitor:20260820-133000

**Review by alexey-milovidov — APPROVED** [review]
The fix looks good.
