### PR TITLE
Do not mix-up send_timeout and receive_timeout

### PR DESCRIPTION
**Pull request by azat**
### Changelog category (leave one):
- Backward Incompatible Change

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Do not mix-up send_timeout and receive_timeout

I've noticed this in one of production setups, where lots of queries are
executed with distributed_group_by_no_merge=2 (automatically vai
optimize_skip_unused_shards optimization) and
optimize_aggregation_in_order=1, with this two settings initiator may
not read from some shards (i.e. X) for quite long period of time,
because it reads from other shards (i.e. Y) and it does not need
any data from X yet (due to it read everything in order), and this will
lead to query timeout, so timeouts had been increased.

Previously both timeouts had been tuned, but this leads to connection
hungs in case of abnormal machine reboots. So it is better to tune only
send_timeout (and this should be enough, since the only problem is the
sender) and this will allow to see that the connection is broken on the
initiator once it will read from this shard.

but after changing only send_timeout, the query still timedout, and the
reason is this place, which swaps this timeouts.

It had been introduced in 134efcd, with a comment:

    NOTE: We use send_timeout for the receive timeout and vice versa (change arguments ordering in TimeoutSetter),
     because send_timeout is client-side setting which has opposite meaning on the server side.

But it sounds odd to me, it may only make sense with the
clickhouse-client, since any other driver does not implement any server
settings.

### CODE REVIEW

**Comment by robot-ch-test-poll1** [comment]
*This is an automated comment for commit 6b90a3f6c6457fce458eb1e3b6aa442d23a98136 with description of existing statuses. It's updated for the latest CI running*

[⏳ Click here](https://s3.amazonaws.com/clickhouse-test-reports/56035/6b90a3f6c6457fce458eb1e3b6aa442d23a98136/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td><a href="https://github.com/ClickHouse/ClickHouse/actions/runs/6650484665">✅ success</a></td></tr>
<tbody>
</table>
</details>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/56035/6b90a3f6c6457fce458eb1e3b6aa442d23a98136/ci_running.html">⏳ pending</a></td></tr>
<tbody>
</table>

**Review by alexey-milovidov — CHANGES_REQUESTED** [review]
> NOTE: We use send_timeout for the receive timeout and vice versa (change arguments ordering in TimeoutSetter),
            ///  because send_timeout is client-side setting which has opposite meaning on the server side.

**Comment by azat** [comment]
I saw the comment, I just don't understand how it could be client-side setting in case of some driver (for c++, python, go...), none of drivers implement settings

**Comment by alexey-milovidov** [comment]
Then, let's change it with the comment. It cannot be a "bug fix" because there is no bug.

**Comment by azat** [comment]
>Then, let's change it with the comment. It cannot be a "bug fix" because there is no bug.

OK, I've changed to `Backward Incompatible Change`, since I guess  there is a little chance that somebody was relying on this.

**Comment by azat** [comment]
All tests failures looks like due to https://github.com/ClickHouse/ClickHouse/issues/56108
And previous CI run passed - https://github.com/ClickHouse/ClickHouse/commit/6b90a3f6c6457fce458eb1e3b6aa442d23a98136

**Review by alexey-milovidov — APPROVED** [review]
