### PR TITLE
Fix debug build

### PR DESCRIPTION
**Pull request by baibaichen**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):

Debug build faild with clang-18 after https://github.com/ClickHouse/ClickHouse/pull/71266, don't know why it's ok in release build, simply changing _ to _1 is ok for both release and debug build.

```
SourceCode/rebase_ch/src/Common/Scheduler/Nodes/UnifiedSchedulerNode.h:497:26: error: declaration shadows a structured binding [-Werror,-Wshadow]
  497 |             for (auto & [_, child] : branch.children)
      |                          ^
/SourceCode/rebase_ch/src/Common/Scheduler/Nodes/UnifiedSchedulerNode.h:495:22: note: previous declaration is here
  495 |         for (auto & [_, branch] : impl.branch.branch.branches)
      |                      ^
```

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by baibaichen** [comment]
@serxa pelase review this

**Comment by robot-clickhouse** [comment]
*This is an automated comment for commit 06a23c0a792642d04b5fcacb7b3e06d85ddd298e with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/71335/06a23c0a792642d04b5fcacb7b3e06d85ddd298e/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/f4a7f475dc1b7619df603e9dfeed189dcd927fbf/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

File: src/Common/Scheduler/Nodes/UnifiedSchedulerNode.h [hunk 1]
```diff
@@ -494,7 +494,7 @@ class UnifiedSchedulerNode final : public ISchedulerNode
             nodes.push_back(impl.branch.queue);
         for (auto & [_, branch] : impl.branch.branch.branches)
```
Comment (nikitamikhaylov) [inline src/Common/Scheduler/Nodes/UnifiedSchedulerNode.h:495]:
```suggestion
        for (auto & [_0, branch] : impl.branch.branch.branches)
```

**Review by nikitamikhaylov — APPROVED** [review]
