### ISSUE TITLE
failing gcc-9 build check since commit 

### ISSUE THREAD

**Issue by bharatnc** [ClickHouse/ClickHouse#14257]
**Operating system**
CI - Sandbox.

gcc-9 -- relwithdebuginfo	 -- none --unbundled --	unsplitted	

**Full cmake and/or ninja output**
https://clickhouse-builds.s3.yandex.net/0/b1efc5df016af083948f4d74118a634197b6be1f/clickhouse_build_check/build_log_759745247_1598751588.txt

Noticed that it has been failing since d9f24b23a63a8c844b2506e8f59e069f1316cfc2 and probably might be related to #13694 
Main error:

```
 2020-08-30 17:45:13 ../base/mysqlxx/Connection.cpp:119:5: error: 'my_bool' was not declared in this scope; did you mean 'bool'?
    2020-08-30 17:45:13   119 |     my_bool reconnect = true;
    2020-08-30 17:45:13       |     ^~~~~~~
    2020-08-30 17:45:13       |     bool
    2020-08-30 17:45:13 ../base/mysqlxx/Connection.cpp:120:90: error: 'reconnect' was not declared in this scope; did you mean 'connect'?
    2020-08-30 17:45:13   120 |     if (mysql_options(driver.get(), MYSQL_OPT_RECONNECT, reinterpret_cast<const char *>(&reconnect)))
    2020-08-30 17:45:13       |                                                                                          ^~~~~~~~~
    2020-08-30 17:45:13       |                                                                                          connect
```

**Comment by bharatnc** [comment]
This has been fixed in #14237, so closing this issue.
