### PR TITLE
Skip engines that store no data in a database-wide `TRUNCATE`

### PR DESCRIPTION
**Pull request by groeneai**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in an official stable release)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Fixed `TRUNCATE ALL TABLES FROM <db>` failing with `NOT_IMPLEMENTED` for the whole database when it held a table whose engine holds no rows of its own (`Merge`, `Null`, `GenerateRandom`, `Executable`, `ExecutablePool`, `FuzzQuery`, `FuzzJSON`, `URL`). Such tables are now skipped, as views and dictionaries already were. Engines that hold rows of their own keep reporting the error.

### Description

Related: https://github.com/ClickHouse/ClickHouse/pull/100943
Related: https://github.com/ClickHouse/ClickHouse/pull/121134

`TRUNCATE ALL TABLES FROM <db>` collects every table whose `IStorage::supportsTruncate()` is true and truncates them in a thread pool, rethrowing the first error. That predicate defaults to `true`, while the `IStorage::truncate()` it falls back to throws `NOT_IMPLEMENTED`. So a single `Merge` or `Null` table fails the statement for the whole database, and since the pool rethrows only after every job has run, the truncatable tables were already emptied: the statement is both rejected and partially applied.

A `false` answer there means "omit me, I have no data of my own", which is why `View`, `Dictionary` and the `URL` scheme dispatcher already return it. This adds the same one-line override to seven engines that hold no rows of their own, so skipping them empties nothing.

`URL` is justified differently: `StorageURL.cpp` already gives the `URL` scheme dispatcher `supportsTruncate() == false` plus a rethrowing `truncate()` so that a `URL` table is never truncated, but plain `StorageURL` was left out, so `URL('file://...')` is skipped today while `URL('http://...')` fails the statement. This completes that decision.

The default stays `true`, so an engine nobody marked keeps today's visible error and is never skipped silently. Engines holding rows of their own, or backed by a system that does (`Buffer`, `MySQL`, `Kafka`, `ODBC`, ...), are deliberately left failing, and the new test pins that. An explicit `TRUNCATE TABLE` never consults the predicate and is unchanged.

Validated on debug builds differing only in these lines: each engine fails before and passes after, removing one override brings back only that engine's error, the excluded engines still fail, and ten truncate-implementing engines are still emptied.

Out of scope: the bulk path is still not atomic when it does fail, which is a property of it for any per-table error rather than of `NOT_IMPLEMENTED` (#120643, #104665).

---
Workflow [[PR](https://s3.amazonaws.com/clickhouse-test-reports/praktika.html?PR=121248&sha=latest&name_0=PR)]
Sync PR [[sync-upstream/pr/121248](https://github.com/search?q=head%3Async-upstream%2Fpr%2F121248+org%3AClickHouse+type%3Apr&type=pullrequests)]

### CODE REVIEW

**Comment by groeneai** [comment]
<details>
<summary><b>Internal second-model review: adjudication log</b> (click to expand)</summary>

Pre-publication review by an independent model (engine: codex; 3 findings) plus my own cold read of the
diff (3 items). Bounded: one full pass, no fix round needed.

| # | Sev | Finding | Verdict | Evidence / action |
|---|-----|---------|---------|---|
| 1 | ❌ | An `Alias` pointing at one of these engines still fails a database-wide `TRUNCATE` (`StorageAlias.h` keeps the default predicate) | DISAGREE for this PR | True at this base, but the sound remedy is a blanket `false` on `Alias`, a different engine and a one-line change of its own: forwarding the target's capability instead would keep truncating a target in another database (`StorageAlias.cpp:299-314`). No regression case for it can be green on both sides of that change, and `Alias` is not in this entry's engine list. Say so and I will move that line here |
| 2 | ❌ | A wildcard `URL` table bypasses the new override and still fails the statement | DISAGREE | That branch returns `StorageObjectStorage` (`StorageURL.cpp:2616-2689`) and needs the experimental `allow_url_wildcard_from_index_pages`, default false (`Settings.cpp:4924`). Its error is `DATABASE_ACCESS_DENIED`, "readonly mode" (`StorageObjectStorage.cpp:916-921`), not the `NOT_IMPLEMENTED` this entry is about, and the carrier is object storage with globs, including `S3` tables holding real objects, where answering `false` would report success over surviving data. Unchanged by this diff; your call if you want it in scope |
| 3 | 💡 | Write `truncate` without parentheses in the test comment | DISAGREE | No such convention: `src/Storages` has 18 comment lines writing a method with parentheses (`apply()`, `read()`, `getSelectedTables()`), stateless tests do the same (`match()`, `count()`), and `StorageURL.cpp:2406` writes `supportsTruncate()` |
| 4 | ⚠️ | `URL` is the one member not justified by storing nothing: an `INSERT` into `URL('http://...')` ships rows to a remote endpoint | Noted, kept | `StorageURLSchemeDispatch` (`StorageURL.cpp:2396-2413`) already answers `false` for a `URL`-declared table whose delegate may be a local `File` or S3 objects, so leaving plain `StorageURL` out only made the behaviour depend on the scheme. Dropping that one line satisfies an objection without touching anything else |
| 5 | 💡 | The precedent and sibling links sat only inside the template's HTML comment | AGREE, fixed before publication | Both `Related:` lines now appear under `### Description` |
| 6 | 💡 | The description said "nine engines that store nothing anywhere" two lines above conceding `URL` is different | AGREE, fixed before publication | Now "eight", with `URL` justified in its own paragraph |

Severity: ❌ blocker / ⚠️ major / 💡 nit. DISAGREE verdicts carry recorded evidence and are terminal per
finding.

</details>

Session id: cron:clickhouse-review-self-slot-58:20260920-223300

File: src/Storages/StorageQueryRunner.h [hunk 1]
```diff
@@ -37,6 +37,8 @@ class StorageQueryRunner final : public IStorage, WithContext
 
     bool supportsParallelInsert() const override { return true; }
 
+    bool supportsTruncate() const override { return false; }
```
[the remark this answers is not in the document]
Comment (groeneai) [reply src/Storages/StorageQueryRunner.h]: Right about the queue, and both halves of the premise hold: `mode` defaults to `ASYNCHRONOUS` (`QueryRunnerSettings.cpp:20`), and `QueryRunnerSink::consume` submits one job per row and, in that mode, returns without waiting for them (`StorageQueryRunner.cpp:703-748`), so a queued query does outlive the `INSERT`.

Where I come out differently is the remedy, because keeping the engine on the failing path does not remove the queued work. Measured on a server, on two debug builds differing only in these overrides (`799198e2` with them, `512ffb1b` without), with one 6 s job holding the single worker thread, one job queued behind it, and a 300 row `MergeTree` sibling in the same database:

| | with the override | without it |
|---|---|---|
| `TRUNCATE ALL TABLES FROM db` | succeeds | `Code: 48 ... NOT_IMPLEMENTED` |
| queued job had run when it returned | no | no |
| queued job ran afterwards | yes, 5.71 s later | yes, 5.72 s later |
| sibling `MergeTree` rows afterwards | 0 | 0 |

The deferred query runs either way, so the error is not what stops it. It only adds the refusal, by which point the sibling table is already empty, which is the defect this PR is about. `TRUNCATE TABLE db.qr` still returns `NOT_IMPLEMENTED` on both builds, so an explicit request is not silently accepted.

What does dispose of the queue is removing the table: `DROP TABLE`, `DETACH TABLE` and `DROP DATABASE` each wait for the running job and discard the queued one (`queued = 0` afterwards, measured on the base build). That path is one way, though, since `shutdown()` latches on `shutdown_called.exchange(true)` and `ThreadPool::finish()` sets `finished` permanently, so a `truncate()` cannot reuse it without giving the table a fresh dispatcher.

What I am not deciding is whether a database holding a `QueryRunner` table should be bulk truncatable at all. If a reviewer would rather this engine keep failing, I will drop that single line; the other engines are independent, and the test controls each one separately. I would add the asynchronous regression in the same change, so that it pins the chosen behaviour rather than a contested one.

I also corrected the description, which called these engines ones that "store nothing anywhere". `QueryRunner` holds no rows of its own, which is what the predicate is about, but it is not stateless.

[the remark this answers is not in the document]
Comment (PedroTadim) [reply src/Storages/StorageQueryRunner.h]: @groeneai let's keep the QueryRunner out of this PR

[the remark this answers is not in the document]
Comment (groeneai) [reply src/Storages/StorageQueryRunner.h]: Done in 1f55460: the `supportsTruncate()` override is out of `StorageQueryRunner.h` and the `QueryRunner` table is out of the test, so the PR is back to the seven engines that hold no rows of their own plus `URL`. Changelog entry and description updated to match.

Verified on the pushed head against a base build differing only in these lines: the test is `[ OK ]` on it and still fails on base (`return code: 48`, `Truncate is not supported by storage Executable`), and `TRUNCATE ALL TABLES FROM <db>` on a database holding a `QueryRunner` table now gives the same `Code: 48 ... Truncate is not supported by storage QueryRunner` on both builds, so that engine is back to master behaviour.

File: tests/queries/0_stateless/05236_truncate_all_tables_skip_engines_without_data.sql [hunk 2]
```diff
@@ -0,0 +1,71 @@
+-- Tags: no-replicated-database
+-- no-replicated-database: TRUNCATE ALL TABLES is not supported for Replicated databases.
+
+-- `TRUNCATE ALL TABLES FROM db` used to fail for the whole database when it held a table whose
+-- engine stores no data and therefore never implemented `truncate()`. Such engines are now skipped,
```
[the remark this answers is not in the document]
Comment (groeneai) [reply tests/queries/0_stateless/05236_truncate_all_tables_skip_engines_without_data.sql:5]: Confirmed in source, and agreed on substance: on this head an `Alias` whose target is one of the marked engines still fails the statement. `StorageAlias` has no `supportsTruncate()` override, and `StorageAlias::truncate` forwards to the target, so the alias entry is still scheduled and the target throws.

Three builds differing only in these lines, one harness. Fixture `db`: `plain` (MergeTree, 300 rows), `e_merge` = `Merge(db, '^plain$')`, `e_null` = `Null`, `a_merge` = `Alias('db', 'e_merge')`, `a_null` = `Alias('db', 'e_null')`. Control `ctl`: same engines, no alias.

| build | `TRUNCATE ALL TABLES FROM db` | `ctl` (no alias) | `TRUNCATE TABLE db.a_merge` |
|---|---|---|---|
| master base `512ffb1b` | debug build aborts: `Logical error: 'RWLockImpl::getLock(): RWLock is already locked in exclusive mode (... which already holds 1 lock(s))'` | `Code: 48 ... storage Merge` | `Code: 48` |
| this PR `33fc568d` | `Code: 48 ... storage Merge` | rc=0 | `Code: 48` |
| this PR + the `Alias` line from #121134, `35db97fa` | rc=0 | rc=0 | `Code: 48` |

Row 1 is why `Alias` is not a member of this census but a separate P0: on master the alias entry and its target entry converge on one storage under one query id, which is an `RWLock` abort rather than a `NOT_IMPLEMENTED` refusal. Marking `Merge` here removes that convergence as a side effect, which is why row 2 is a plain error. The explicit path is `Code: 48` in all three arms, so nothing is silently accepted.

Row 3 is the contract you ask for. It already exists, with its regression test, in #121134, approved and labelled `pr-critical-bugfix` / `pr-must-backport`, and the placement was ruled on in https://github.com/ClickHouse/ClickHouse/pull/121134#discussion_r4059267813 about six hours before this comment: that PR stays the one-header P0, this one carries the capability census. I measured the merge interaction instead of assuming it, and #121134's hunk applies cleanly to this head, so neither order conflicts.

So I am not adding the line here: it would put the same one-line change in two open PRs, one of them a must-backport, and this PR's scope was narrowed by a reviewer earlier today. If a reviewer prefers it here, I will move it with its regression case and drop it from #121134.

**Comment by groeneai** [comment]
### CI finish ledger - 1f55460a7b471e445521c1d3fce459d03bf3f7cb

Every failure below has an owner: a fixing PR, or a full-effort fix task whose fixing-PR link gets posted here when it opens.

| Check / test | Reason | Owner / fixing PR |
|---|---|---|
| Stateless tests (arm_asan_ubsan, targeted) / `05227_ast_fuzzer_no_profile_events_leak` | flaky, and the throw is in the server-side fuzzer rather than in the test's SQL: three `QueryFuzzer` mutations call `ASTTableIdentifier::getTableId()` on a parameterized table identifier, `StorageID::assertNotEmpty()` throws `UNKNOWN_TABLE`, the fuzzer logs it at `<Error>`, and the test's clean-stderr oracle reds. 1 FAIL in 1,092 runs across 99 PRs over 30 days; this diff touches nothing on that path | [#115786](https://github.com/ClickHouse/ClickHouse/pull/115786) (mine, open) adds the `isParam()` guard at all three call sites |
| Performance Comparison (arm_release, master_head, 1/6) | `1 confirmed regression(s) on the performance dashboard`, while the shard's own report calls no query `slower` or `unstable`. That dashboard-verdict gate reds unrelated PRs: 53 runs across 50 distinct PRs in the last 24 hours | [#121090](https://github.com/ClickHouse/ClickHouse/pull/121090) (mine, open) fails a `master_head` shard only when its own report also calls the query slower |
| Mergeable Check, PR | praktika aggregators, mirroring the two rows above rather than failing independently | [#115786](https://github.com/ClickHouse/ClickHouse/pull/115786) + [#121090](https://github.com/ClickHouse/ClickHouse/pull/121090) (both mine, open): these two aggregators go green once the two rows above do |

CI is fully finished on this head: 176 contexts, 133 success, 39 skipped, 4 failures, all listed.

Session id: cron:our-pr-ci-monitor:20260921-153146

**Review by PedroTadim — APPROVED** [review]
