### PR TITLE
fix clang 18 build

### PR DESCRIPTION
**Pull request by baibaichen**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)
clang 18 build failed after #73324 , not sure why its' ok in clang19, it looks like clang18 more strict than clang19.

```
/src/Functions/formatDateTime.cpp:509:44: error: implicit conversion loses integer precision: 'UInt64' (aka 'unsigned long') to 'UInt32' (aka 'unsigned int') [-Werror,-Wshorten-64-to-32]
  509 |             for (UInt32 i = scale, value = fractional_second; i > 0 && value > 0; --i)
      |                                    ~~~~~   ^~~~~~~~~~~~~~~~~
```

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
...

### Documentation entry for user-facing changes

- [ ] Documentation is written (mandatory for new features)

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing)

All builds in Builds_1 and Builds_2 stages are always mandatory
and will run independently of the checks below:

- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64
- [ ]  Exclude: All with release
- [ ]  Exclude: All with debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by baibaichen** [comment]
@ollidraese @rschu1ze please review this

**Comment by yakov-olkhovskiy** [comment]
duplicate of #73324
