### PR TITLE
Fix build errors on clang15 in CapnProtoSerializer

### LINKED ISSUE #50963: Clang 15 Build failed after #49752
Using Clang 15 build latest code with #49752 will failed:
```

[2023-06-13T23:38:02.611Z] /ClickHouse/src/Formats/CapnProtoSerializer.cpp:754:9: error: missing 'typename' prior to dependent type name 'CapnpType::Reader'
[2023-06-13T23:38:02.611Z]         CapnpType::Reader getData(const ColumnPtr & column, size_t row_num)
[2023-06-13T23:38:02.611Z]         ^~~~~~~~~~~~~~~~~
[2023-06-13T23:38:02.611Z]         typename 
[2023-06-13T23:38:02.611Z] /ClickHouse/src/Formats/CapnProtoSerializer.cpp:804:9: error: missing 'typename' prior to dependent type name 'CapnpType::Reader'
[2023-06-13T23:38:02.611Z]         CapnpType::Reader getData(const ColumnPtr & column, size_t row_num)
[2023-06-13T23:38:02.611Z]         ^~~~~~~~~~~~~~~~~
[2023-06-13T23:38:02.611Z]         typename 
```

Clang 16 is ok

### PR DESCRIPTION
**Pull request by al13n321**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

I'm getting these errors: https://pastila.nl/?005ea3d4/2ee24fb084b8be392a98efdd4d418000

(Not sure what's the difference between my machine and everybody else's + CI, where builds apparently succeed. Maybe I'm the only one still on clang 15?)

Closes https://github.com/ClickHouse/ClickHouse/issues/50963

### CODE REVIEW

**Comment by robot-ch-test-poll4** [comment]
This is an automated comment for commit b09d63bf33a757d1abbd668f144fb4113ac66989 with description of existing statuses. It's updated for the latest CI running
The full report is available [here](https://s3.amazonaws.com/clickhouse-test-reports/51021/b09d63bf33a757d1abbd668f144fb4113ac66989/ci_running.html)
The overall status of the commit is 🟡 pending

<table><thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody><tr><td>CI running</td><td>A meta-check that indicates the running CI. Normally, it's in <b>success</b> or <b>pending</b> state. The failed status indicates some problems with the PR</td><td>🟡 pending</td></tr>
<tr><td>Mergeable Check</td><td>Checks if all other necessary checks are successful</td><td>🟢 success</td></tr>
</table>

**Review by Avogar — APPROVED** [review]

**Comment by Avogar** [comment]
Thanks! We use clang-16 in CI and I use it locally, so, I didn't know about this issue

**Comment by antonio2368** [comment]
https://github.com/ClickHouse/ClickHouse/pull/50967 he was first so maybe close this one? 😅

**Comment by antonio2368** [comment]
Duplicate of https://github.com/ClickHouse/ClickHouse/pull/50967
