### PR TITLE
Fix debug build in clang-18

### PR DESCRIPTION
**Pull request by baibaichen**
### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Debug build  faild with clang-18 after https://github.com/ClickHouse/ClickHouse/pull/70412,  don't know why it's ok in release build, simply changing `_` to `_1` is ok for both release and debug build.

```
../ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp
../ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:1964:56: error: declaration shadows a local variable [-Werror,-Wshadow]
 1964 |             for (auto & [table_expression_column_node, _] : table_expression_column_nodes_with_names)
      |                                                        ^
../ClickHouse/src/Analyzer/Resolve/QueryAnalyzer.cpp:1953:40: note: previous declaration is here
 1953 |         if (auto * /*array_join_node*/ _ = table_expression->as<ArrayJoinNode>())
```

> Information about CI checks: https://clickhouse.com/docs/en/development/continuous-integration/

#### CI Settings (Only check the boxes if you know what you are doing):
- [ ]  Allow: All Required Checks
- [ ]  Allow: Stateless tests
- [ ]  Allow: Stateful tests
- [ ]  Allow: Integration Tests
- [ ]  Allow: Performance tests
- [ ]  Allow: All Builds
- [ ]  Allow: batch 1, 2 for multi-batch jobs
- [ ]  Allow: batch 3, 4, 5, 6 for multi-batch jobs
---
- [ ]  Exclude: Style check
- [ ]  Exclude: Fast test
- [ ]  Exclude: All with ASAN
- [ ]  Exclude: All with TSAN, MSAN, UBSAN, Coverage
- [ ]  Exclude: All with aarch64, release, debug
---
- [ ]  Run only fuzzers related jobs (libFuzzer fuzzers, AST fuzzers, etc.)
- [ ]  Exclude: AST fuzzers
---
- [ ]  Do not test
- [ ]  Woolen Wolfdog
- [ ]  Upload binaries for special builds
- [ ]  Disable merge-commit
- [ ]  Disable CI cache

### CODE REVIEW

**Comment by baibaichen** [comment]
@thevar1able could you please review this pr?

**Comment by robot-ch-test-poll4** [comment]
*This is an automated comment for commit cc7d4c80baf28026189038d9dd31d4a81ac7bb44 with description of existing statuses. It's updated for the latest CI running*

[✅ Click here](https://s3.amazonaws.com/clickhouse-test-reports/70532/cc7d4c80baf28026189038d9dd31d4a81ac7bb44/ci_running.html) to open a full report in a separate page

<details><summary>Successful checks</summary>
<table>
<thead><tr><th>Check name</th><th>Description</th><th>Status</th></tr></thead>
<tbody>
<tr><td>Docs check</td><td>Builds and tests the documentation</td><td><a href="https://s3.amazonaws.com/clickhouse-test-reports/0/e9a1ac5ff4a88eab38cd97bec1e303495e99f548/docs_check.html">✅ success</a></td></tr>
<tbody>
</table>
</details>

**Review by thevar1able — APPROVED** [review]
