### PR TITLE
Fix usage/linking of static dbms library (add clickhouse_aggregate_functions)

### PR DESCRIPTION
**Pull request by azat**
Changelog category (leave one):
- Not for changelog (changelog entry is not required)

The following error reported:

```
    FAILED: src/Interpreters/tests/hash_map
    ...
    ld.lld: error: undefined symbol: typeinfo for DB::AggregateFunctionCount
    >>> referenced by typeinfo:308 (../contrib/libcxx/include/typeinfo:308)
    >>>               InterpreterSelectQuery.cpp.o:(std::__1::enable_if<is_pointer_v<DB::AggregateFunctionCount*>, DB::AggregateFunctionCount*>::type typeid_cast<DB::AggregateFunctionCount*, DB::IAggregateFunction>(DB::IAggregateFunction*)) in archive src/libdbms.a
    collect2: error: ld returned 1 exit status
```

And also this one with gold linker:

```
  FAILED: programs/clickhouse-odbc-bridge
  ...  src/AggregateFunctions/libclickhouse_aggregate_functions.a ... src/libdbms.a ...
  ../contrib/libcxx/include/typeinfo:308: error: undefined reference to 'typeinfo for DB::AggregateFunctionCount'
```

Due to order?

Introduced by 394fb64a9cda376ca8dfa8bac08a4fbcfa9bf3bf/#11661 I guess.

Cc: @alexey-milovidov (author of PR)

### CODE REVIEW

**Comment by alexey-milovidov** [comment]
How it happened to succeed in CI?

**Comment by alexey-milovidov** [comment]
Alternative solution: as aggregate function `count` is used not only through the factory and we have direct dependency, we can move its implementation to `dbms` library out of `clickhouse_aggregate_functions`.

**Comment by azat** [comment]
>How it happened to succeed in CI?

This is interesting, I don't know for sure, will take a look later

>Alternative solution: as aggregate function count is used not only through the factory and we have direct dependency, we can move its implementation to dbms library out of clickhouse_aggregate_functions.

But this will have excludes in different cmake levels... Hm, I see that this is already there, ok will add one more file there

**Comment by azat** [comment]
>How it happened to succeed in CI?

Here are some differences:
- gold linker for one error
- lld-8 for another (while there is lld-10 on CI)

**Comment by alexey-milovidov** [comment]
> test_always_fetch_merged/test.py::test_replica_always_download

Flaky test.

**Review by alexey-milovidov — APPROVED** [review]
