### PR TITLE
Hermetic builds

### LINKED ISSUE #21435: Unable to run integration tests if Ubuntu 20.10 host
Ubuntu 20.10 has glibc 2.32 and ClickHouse built in a plain way has two symbols marked GLIBC_2.32,
namely
 
```
 ilejn@ilejn-Latitude-5400:~/projects/ClickHouse/build$ objdump -T ./programs/clickhouse | grep GLIBC_2.32
 0000000000000000      DF *UND*  0000000000000000  GLIBC_2.32  pthread_sigmask
 0000000000000000      DF *UND*  0000000000000000  GLIBC_2.32  pthread_getattr_np
```

### LINKED ISSUE #27133: GLIBC 2.32 / 2.33 / 2.34 compatibility
It would be nice if Clickhouse supported building in an enviornment with GLIBC 2.32+ like it supports older releases (pinning symbols).

My usecase is that I'm building in a new machine (Archlinux with GLIBC 2.33) and that works great until I want to run the integration tests, which run under an old Ubuntu (20.04) with 2.31-0ubuntu9.2 and that will fail when using the binary:

```
E               Exception: Timed out while waiting for instance `node1' with ip address 172.16.0.4 to start. Container status: running, logs: clickhouse: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by clickhouse)
E               clickhouse: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by clickhouse)
```

I see that @amosbird started working on it but ended up discarding the PR (https://github.com/ClickHouse/ClickHouse/pull/24015). I've tested it and it doesn't work for 2.33.

Are there any plans to support this or should I look for a better way to run those tests locally?

### LINKED ISSUE #30462: `__pthread_mutex_(lock|unlock)` are not exported in glibc 2.34
**Operating system**

openSUSE Tumbleweed
glibc 2.34

**Cmake version**

cmake 3.21.3

**Ninja version**

ninja 1.10.2

**Compiler name and version**

gcc 11.2.1

**Full cmake and/or ninja output**

```
[  436s] + /usr/bin/cmake /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/. -GNinja -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DCMAKE_INSTALL_LIBDIR:PATH=lib64 -DCMAKE_INSTALL_LIBEXECDIR=/usr/libexec -DCMAKE_BUILD_TYPE=RelWithDebInfo '-DCMAKE_C_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type  -g -DNDEBUG' '-DCMAKE_CXX_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type  -g -DNDEBUG' '-DCMAKE_Fortran_FLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type  -g -DNDEBUG' '-DCMAKE_EXE_LINKER_FLAGS= -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' '-DCMAKE_MODULE_LINKER_FLAGS= -Wl,--as-needed' '-DCMAKE_SHARED_LINKER_FLAGS= -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now' -DLIB_SUFFIX=64 -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DBUILD_SHARED_LIBS:BOOL=ON -DBUILD_STATIC_LIBS:BOOL=OFF -DCMAKE_COLOR_MAKEFILE:BOOL=OFF -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_MODULES_INSTALL_DIR=/usr/lib64/cmake/clickhouse -DARCH_NATIVE:BOOL=OFF -DBUILD_SHARED_LIBS:BOOL=OFF -DBUILD_STATIC_LIBS:BOOL=ON -DCOMPILER_PIPE:BOOL=OFF -DDISABLE_CPU_OPTIMIZE:BOOL=ON -DENABLE_AVRO:BOOL=OFF -DENABLE_CCACHE:BOOL=OFF -DENABLE_EMBEDDED_COMPILER:BOOL=OFF -DENABLE_FASTOPS:BOOL=OFF -DENABLE_GRPC:BOOL=OFF -DENABLE_PARQUET:BOOL=OFF -DENABLE_ROCKSDB:BOOL=OFF -DENABLE_S3:BOOL=OFF -DENABLE_TESTS:BOOL=OFF -DGLIBC_COMPATIBILITY:BOOL=OFF -DPARALLEL_COMPILE_JOBS=6 -DPARALLEL_LINK_JOBS=1 -DUNBUNDLED:BOOL=ON -DUSE_INTERNAL_BOOST_LIBRARY:BOOL=OFF -DUSE_INTERNAL_CAPNP_LIBRARY:BOOL=OFF -DUSE_INTERNAL_CCTZ_LIBRARY:BOOL=ON -DUSE_INTERNAL_FARMHASH_LIBRARY:BOOL=ON -DUSE_INTERNAL_ICU_LIBRARY:BOOL=OFF -DUSE_INTERNAL_JEMALLOC_LIBRARY:BOOL=OFF -DUSE_INTERNAL_LIBCXX_LIBRARY:BOOL=OFF -DUSE_INTERNAL_LIBGSASL_LIBRARY:BOOL=OFF -DUSE_INTERNAL_LIBXML2_LIBRARY:BOOL=OFF -DUSE_INTERNAL_LLVM_LIBRARY:BOOL=OFF -DUSE_INTERNAL_MYSQL_LIBRARY:BOOL=OFF -DUSE_INTERNAL_ODBC_LIBRARY:BOOL=OFF -DUSE_INTERNAL_POCO_LIBRARY:BOOL=ON -DUSE_INTERNAL_RDKAFKA_LIBRARY:BOOL=OFF -DUSE_INTERNAL_RE2_LIBRARY:BOOL=OFF -DUSE_INTERNAL_SSL_LIBRARY:BOOL=OFF -DUSE_INTERNAL_ZLIB_LIBRARY:BOOL=OFF -DUSE_LIBCXX:BOOL=OFF -DUSE_SIMDJSON:BOOL=OFF -DWERROR:BOOL=OFF
[  436s] -- The C compiler identification is GNU 11.2.1
[  436s] -- The CXX compiler identification is GNU 11.2.1
[  436s] -- Detecting C compiler ABI info
[  436s] -- Detecting C compiler ABI info - done
[  436s] -- Check for working C compiler: /var/lib/build/ccache/bin/cc - skipped
[  436s] -- Detecting C compile features
[  436s] -- Detecting C compile features - done
[  436s] -- Detecting CXX compiler ABI info
[  437s] -- Detecting CXX compiler ABI info - done
[  437s] -- Check for working CXX compiler: /var/lib/build/ccache/bin/c++ - skipped
[  437s] -- Detecting CXX compile features
[  437s] -- Detecting CXX compile features - done
[  437s] -- The ASM compiler identification is GNU
[  437s] -- Found assembler: /var/lib/build/ccache/bin/cc
[  437s] CMake Warning at cmake/tools.cmake:16 (message):
[  437s]   GCC compiler is not officially supported for ClickHouse.  You should
[  437s]   migrate to clang.
[  437s] Call Stack (most recent call first):
[  437s]   CMakeLists.txt:46 (include)
[  437s] 
[  437s] 
[  437s] -- Using custom linker by name: gold
[  437s] -- CMAKE_BUILD_TYPE: RelWithDebInfo
[  437s] -- Using objcopy: /usr/bin/llvm-objcopy
[  437s] -- Disabling compiler -pipe option (have only 30849 mb of memory)
[  437s] -- Performing Test HAVE_SSE41
[  437s] -- Performing Test HAVE_SSE41 - Success
[  437s] -- Performing Test HAVE_SSE42
[  437s] -- Performing Test HAVE_SSE42 - Success
[  437s] -- Performing Test HAVE_SSSE3
[  437s] -- Performing Test HAVE_SSSE3 - Success
[  437s] -- Performing Test HAVE_AVX
[  438s] -- Performing Test HAVE_AVX - Success
[  438s] -- Performing Test HAVE_AVX2
[  439s] -- Performing Test HAVE_AVX2 - Success
[  439s] -- Performing Test HAVE_PCLMULQDQ
[  439s] -- Performing Test HAVE_PCLMULQDQ - Success
[  439s] -- Performing Test HAVE_POPCNT
[  440s] -- Performing Test HAVE_POPCNT - Success
[  440s] -- Default libraries: -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl
[  440s] -- Looking for pthread.h
[  440s] -- Looking for pthread.h - found
[  440s] -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
[  440s] -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
[  440s] -- Found Threads: TRUE  
[  440s] -- Performing Test HAVE_WARNING_UNUSED_BUT_SET_VARIABLE
[  440s] -- Performing Test HAVE_WARNING_UNUSED_BUT_SET_VARIABLE - Success
[  440s] -- Performing Test HAVE_WARNING_MISSING_ATTRIBUTES
[  440s] -- Performing Test HAVE_WARNING_MISSING_ATTRIBUTES - Success
[  440s] -- Performing Test HAVE_WARNING_MAYBE_UNINITIALIZED
[  440s] -- Performing Test HAVE_WARNING_MAYBE_UNINITIALIZED - Success
[  440s] -- Performing Test HAVE_WARNING_REGISTER
[  440s] -- Performing Test HAVE_WARNING_REGISTER - Success
[  440s] -- Using libunwind: unwind
[  440s] -- Using exception handler: unwind
[  440s] -- Unit tests are disabled
[  440s] -- Building for: Linux-5.14.11-1-default x86_64  ;
[  440s]     USE_STATIC_LIBRARIES=ON
[  440s]     MAKE_STATIC_LIBRARIES=ON
[  440s]     SPLIT_SHARED=
[  440s]     UNBUNDLED=ON
[  440s]     CCACHE= 
[  440s] CMake Warning (dev) at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
[  440s]   The package name passed to `find_package_handle_standard_args`
[  440s]   (double_conversion) does not match the name of the calling package
[  440s]   (double-conversion).  This can lead to problems in calling code that
[  440s]   expects `find_package` result variables (e.g., `_FOUND`) to follow a
[  440s]   certain pattern.
[  440s] Call Stack (most recent call first):
[  440s]   cmake/Modules/Finddouble-conversion.cmake:35 (find_package_handle_standard_args)
[  440s]   cmake/contrib_finder.cmake:10 (find_package)
[  440s]   CMakeLists.txt:501 (find_contrib_lib)
[  440s] This warning is for project developers.  Use -Wno-dev to suppress it.
[  440s] 
[  440s] -- Found double_conversion: /usr/lib64/libdouble-conversion.so  
[  440s] -- Using double-conversion: /usr/include : /usr/lib64/libdouble-conversion.so
[  441s] -- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY) (found version "1.1.1l")
[  441s] -- Using ssl=1: /usr/include : /usr/lib64/libssl.so;/usr/lib64/libcrypto.so
[  441s] -- Found the following ICU libraries:
[  441s] --   i18n (required)
[  441s] --   uc (required)
[  441s] --   data (required)
[  441s] -- Found ICU: /usr/include (found version "69.1") 
[  441s] -- Using icu=1: /usr/include : /usr/lib64/libicui18n.so;/usr/lib64/libicuuc.so;/usr/lib64/libicudata.so
[  441s] -- Using xz (lzma): /usr/include : /usr/lib64/liblzma.so
[  441s] -- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11") 
[  441s] -- Using libz: /usr/include : /usr/lib64/libz.so
[  441s] -- Using zstd: /usr/include : /usr/lib64/libzstd.so
[  441s] -- Using sparsehash: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/sparsehash-c11
[  441s] -- Using re2: /usr/include : /usr/lib64/libre2.so;  : /usr/lib64/libre2.so
[  441s] -- Using krb5=1: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/krb5/src/include;/home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/build/contrib/krb5-cmake/include : krb5
[  441s] -- Using libgsasl=1: /usr/include : /usr/lib64/libgsasl.so
[  441s] -- Using cyrus-sasl: krb5=1: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/cyrus-sasl/include : sasl2
[  441s] -- Using librdkafka=1: /usr/include : rdkafka_imp;/usr/lib64/libssl.so;/usr/lib64/libcrypto.so;/usr/lib64/libsasl2.so cppkafka
[  441s] -- Using libuv: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/libuv : uv_a
[  441s] -- Using AMQP-CPP=1: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/AMQP-CPP/include;/home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/libuv/include;/home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/AMQP-CPP : amqp-cpp;uv_a
[  441s] -- Using capnp=1: /usr/lib64/libcapnpc.so;/usr/lib64/libcapnp.so;/usr/lib64/libkj.so
[  441s] -- Using h3=1: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/h3/src/h3lib/include : h3
[  441s] -- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.12") 
[  441s] -- Looking for lzma_auto_decoder in /usr/lib64/liblzma.so
[  441s] -- Looking for lzma_auto_decoder in /usr/lib64/liblzma.so - found
[  441s] -- Looking for lzma_easy_encoder in /usr/lib64/liblzma.so
[  441s] -- Looking for lzma_easy_encoder in /usr/lib64/liblzma.so - found
[  441s] -- Looking for lzma_lzma_preset in /usr/lib64/liblzma.so
[  441s] -- Looking for lzma_lzma_preset in /usr/lib64/liblzma.so - found
[  441s] -- Found LibLZMA: /usr/lib64/liblzma.so (found version "5.2.5") 
[  441s] -- Using libxml2: /usr/include/libxml2 : /usr/lib64/libxml2.so;/usr/lib64/liblzma.so
[  441s] -- Using brotli=1: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/brotli/c/include : brotli
[  441s] -- Found Protobuf: /usr/lib64/libprotobuf.so (found version "3.17.3") 
[  441s] -- Using protobuf=1: /usr/include : /usr/lib64/libprotobuf.so : /usr/bin/protoc : /usr/lib64/libprotoc.so
[  441s] -- Using pdqsort: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/pdqsort
[  441s] -- Using miniselect: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/miniselect/include
[  441s] -- Using hdfs3=1: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/libhdfs3/include : hdfs3
[  441s] -- Found CURL: /usr/lib64/libcurl.so (found version "7.79.1")  
[  441s] -- Using curl: /usr/include : /usr/lib64/libcurl.so
[  441s] -- Building without Parquet support
[  441s] -- Using simdjson=OFF
[  441s] -- Using rapidjson=1: /usr/include
[  441s] -- Found odbc: /usr/lib64/libodbc.so
[  441s] -- Using unixodbc
[  441s] -- Using nanodbc: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/nanodbc/nanodbc : nanodbc
[  441s] -- Using NuRaft=1: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/NuRaft/include : nuraft
[  441s] -- Using msgpack=1: /usr/include
[  441s] -- Using cassandra=1: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/cassandra/include/ : cassandra_static
[  441s] -- Using stats=1 : /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/stats/include
[  441s] -- Using gcem=1: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/contrib/gcem/include
[  441s] -- Using datasketches=: DATASKETCHES_INCLUDE_DIR-NOTFOUND : DATASKETCHES_LIBRARY-NOTFOUND
[  441s] -- Using cityhash:  : cityhash
[  441s] -- Using farmhash:  : farmhash
[  441s] -- Using mysqlclient=1: /usr/include/mysql : ; staticlib=/usr/lib64/libmysqlclient.so
[  441s] -- compiler C   = /var/lib/build/ccache/bin/cc -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type  -g -DNDEBUG -fdiagnostics-color=always  -msse4.1 -msse4.2 -mpopcnt -fasynchronous-unwind-tables -falign-functions=32  -Wall  -O2 -g -DNDEBUG -O3  -fno-pie
[  441s] -- compiler CXX = /var/lib/build/ccache/bin/c++ -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type  -g -DNDEBUG -fdiagnostics-color=always -fsized-deallocation  -msse4.1 -msse4.2 -mpopcnt -fasynchronous-unwind-tables -falign-functions=32   -Wall  -O2 -g -DNDEBUG -O3  -fno-pie
[  441s] -- LINKER_FLAGS =  -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -fuse-ld=gold -rdynamic -Wl,--no-undefined -Wl,-no-pie 
[  442s] -- Found Boost: /usr/lib64/cmake/Boost-1.77.0/BoostConfig.cmake (found suitable version "1.77.0", minimum required is "1.71") found components: system filesystem iostreams program_options regex context coroutine 
[  442s] -- Packaging with tzdata version: 2020e
[  442s] -- Using cctz
[  442s] -- Using hyperscan
[  442s] -- jemalloc malloc_conf: percpu_arena:percpu,oversize_threshold:0,muzzy_decay_ms:5000,dirty_decay_ms:5000
[  442s] -- Using jemalloc
[  442s] -- Using cpuid
[  442s] -- Using replxx
[  442s] -- Using Poco::Crypto
[  442s] -- Using Poco::Data::ODBC
[  442s] -- checking compiler: GCC (11.2.)
[  442s] -- Looking for dladdr
[  442s] -- Looking for dladdr - found
[  442s] -- Looking for nanosleep
[  442s] -- Looking for nanosleep - found
[  442s] -- Checking whether strerror_r returns an int
[  442s] -- Checking whether strerror_r returns an int -- no
[  443s] -- libuv version: v1.34.1
[  443s] -- Found Libuv: uv_a (found suitable version "1.34.1", minimum required is "1.0.0") 
[  443s] -- Found OpenSSL: /usr/lib64/libssl.so (found version "1.1.1l") 
[  443s] -- OpenSSL version: v1.1.1l
[  443s] -- Could NOT find CLANG_FORMAT (missing: CLANG_FORMAT_EXE) 
[  443s] -- Unable to find clang-format. Not creating format targets.
[  443s] -- Driver version: 2.15.3
[  443s] -- Using std::atomic implementation for atomic operations
[  443s] -- Checking to see if CXX compiler accepts flag -std=c++11
[  444s] -- Checking to see if CXX compiler accepts flag -std=c++11 - yes
[  445s] -- Using hash header <functional> and namespace "std"
[  445s] -- Looking for inttypes.h
[  445s] -- Looking for inttypes.h - found
[  445s] -- Looking for stdint.h
[  445s] -- Looking for stdint.h - found
[  445s] -- Looking for sys/types.h
[  445s] -- Looking for sys/types.h - found
[  445s] -- Looking for memcpy
[  445s] -- Looking for memcpy - found
[  445s] -- Looking for stddef.h
[  445s] -- Looking for stddef.h - found
[  445s] -- Check size of long long
[  445s] -- Check size of long long - done
[  445s] -- Check size of uint16_t
[  446s] -- Check size of uint16_t - done
[  446s] -- Check size of u_int16_t
[  446s] -- Check size of u_int16_t - done
[  446s] -- Check size of __uint16_t
[  446s] -- Check size of __uint16_t - done
[  446s] -- Looking for GRND_NONBLOCK
[  446s] -- Looking for GRND_NONBLOCK - found
[  446s] -- Looking for SO_NOSIGPIPE
[  446s] -- Looking for SO_NOSIGPIPE - not found
[  446s] -- Looking for sigtimedwait
[  446s] -- Looking for sigtimedwait - found
[  446s] -- Performing Test HAVE_BUILTIN_BSWAP32
[  447s] -- Performing Test HAVE_BUILTIN_BSWAP32 - Success
[  447s] -- Performing Test HAVE_BUILTIN_BSWAP64
[  447s] -- Performing Test HAVE_BUILTIN_BSWAP64 - Success
[  447s] -- GCE-Math version 1.13.0
[  447s] -- Performing Test SUPPORTS_CXXFLAG_frame_larger_than=65536
[  447s] -- Performing Test SUPPORTS_CXXFLAG_frame_larger_than=65536 - Success
[  447s] -- Performing Test SUPPORTS_CFLAG_frame_larger_than=65536
[  447s] -- Performing Test SUPPORTS_CFLAG_frame_larger_than=65536 - Success
[  447s] -- Performing Test HAS_SUGGEST_DESTRUCTOR_OVERRIDE
[  447s] -- Performing Test HAS_SUGGEST_DESTRUCTOR_OVERRIDE - Failed
[  447s] -- Performing Test HAS_SHADOW
[  447s] -- Performing Test HAS_SHADOW - Success
[  447s] -- Performing Test HAS_SUGGEST_OVERRIDE
[  447s] -- Performing Test HAS_SUGGEST_OVERRIDE - Success
[  447s] CMake Warning at base/mysqlxx/CMakeLists.txt:53 (message):
[  447s]   Statically linking with system mysql/mariadb only works if mysql client
[  447s]   libraries are built with same openssl version as we are going to use now.
[  447s]   It wouldn't work if GnuTLS is used.  Try -D"USE_INTERNAL_MYSQL_LIBRARY"=ON
[  447s]   or -D"ENABLE_MYSQL"=OFF or -D"USE_STATIC_LIBRARIES"=OFF
[  447s] 
[  447s] 
[  448s] -- /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/src: Have 30816 megabytes of memory.
[  448s]         Limiting concurrent linkers jobs to 1 and compiler jobs to 6
[  448s] -- Will build ClickHouse 21.8.9.1 revision 54453 
[  448s] CMake Warning at src/Functions/CMakeLists.txt:54 (message):
[  448s]   Not generating debugger info for ClickHouse functions
[  448s] 
[  448s] 
[  448s] -- ClickHouse modes:
[  448s] -- Server mode: ON
[  448s] -- Client mode: ON
[  448s] -- Local mode: ON
[  448s] -- Benchmark mode: ON
[  448s] -- Extract from config mode: ON
[  448s] -- Compressor mode: ON
[  448s] -- Copier mode: ON
[  448s] -- Format mode: ON
[  448s] -- Obfuscator mode: ON
[  448s] -- ODBC bridge mode: ON
[  448s] -- Library bridge mode: ON
[  448s] -- ClickHouse install: ON
[  448s] -- ClickHouse git-import: ON
[  448s] -- ClickHouse keeper mode: ON
[  448s] -- ClickHouse keeper-converter mode: ON
[  448s] -- bash_completion will be written to /usr/share/bash-completion/completions
[  448s] -- Target check already exists
[  448s] -- /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/utils: Have 30813 megabytes of memory.
[  448s]         Limiting concurrent linkers jobs to 1 and compiler jobs to 6
[  448s] -- Configuring done
[  450s] -- Generating done
[  450s] CMake Warning:
[  450s]   Manually-specified variables were not used by the project:
[  450s] 
[  450s]     BUILD_STATIC_LIBS
[  450s]     CMAKE_COLOR_MAKEFILE
[  450s]     CMAKE_Fortran_FLAGS
[  450s]     CMAKE_INSTALL_DO_STRIP
[  450s]     CMAKE_MODULES_INSTALL_DIR
[  450s]     CMAKE_VERBOSE_MAKEFILE
[  450s]     DISABLE_CPU_OPTIMIZE
[  450s]     INCLUDE_INSTALL_DIR
[  450s]     LIB_INSTALL_DIR
[  450s]     LIB_SUFFIX
[  450s]     SHARE_INSTALL_PREFIX
[  450s]     SYSCONF_INSTALL_DIR
[  450s]     USE_INTERNAL_JEMALLOC_LIBRARY
[  450s] 
[  450s] 
[  450s] -- Build files have been written to: /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/build

```

skipped unrelated

```
[ 7546s] FAILED: programs/clickhouse-library-bridge 
[ 7546s] : && /var/lib/build/ccache/bin/c++ -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type  -g -DNDEBUG -fdiagnostics-color=always -fsized-deallocation  -msse4.1 -msse4.2 -mpopcnt -fasynchronous-unwind-tables -falign-functions=32   -Wall  -Wextra -Wframe-larger-than=65536 -O2 -g -DNDEBUG -O3  -fno-pie -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -fuse-ld=gold -rdynamic -Wl,--no-undefined -Wl,-no-pie -Wl,--no-export-dynamic   -rdynamic src/CMakeFiles/clickhouse_malloc.dir/Common/malloc.cpp.o programs/library-bridge/CMakeFiles/clickhouse-library-bridge.dir/library-bridge.cpp.o programs/library-bridge/CMakeFiles/clickhouse-library-bridge.dir/LibraryInterface.cpp.o programs/library-bridge/CMakeFiles/clickhouse-library-bridge.dir/LibraryBridge.cpp.o programs/library-bridge/CMakeFiles/clickhouse-library-bridge.dir/Handlers.cpp.o programs/library-bridge/CMakeFiles/clickhouse-library-bridge.dir/HandlerFactory.cpp.o programs/library-bridge/CMakeFiles/clickhouse-library-bridge.dir/SharedLibraryHandler.cpp.o programs/library-bridge/CMakeFiles/clickhouse-library-bridge.dir/SharedLibraryHandlerFactory.cpp.o -o programs/clickhouse-library-bridge  src/libclickhouse_new_delete.a  base/daemon/libdaemon.a  src/libdbms.a  base/bridge/libbridge.a  base/daemon/libdaemon.a  base/loggers/libloggers.a  src/libdbms.a  contrib/jemalloc-cmake/libjemalloc.a  src/Common/Config/libclickhouse_common_config.a  contrib/yaml-cpp-cmake/libyaml-cpp.a  contrib/cppkafka-cmake/libcppkafka.a  /usr/lib64/librdkafka.so  /usr/lib64/libsasl2.so  contrib/cyrus-sasl-cmake/libsasl2.a  contrib/nuraft-cmake/libnuraft.a  /usr/lib64/libboost_coroutine.so.1.77.0  /usr/lib64/libboost_chrono.so.1.77.0  /usr/lib64/libboost_thread.so.1.77.0  /usr/lib64/libboost_filesystem.so.1.77.0  /usr/lib64/libboost_atomic.so.1.77.0  src/Common/ZooKeeper/libclickhouse_common_zookeeper.a  src/Dictionaries/Embedded/libclickhouse_dictionaries_embedded.a  src/Parsers/libclickhouse_parsers.a  src/libclickhouse_common_io.a  /usr/lib64/libboost_program_options.so.1.77.0  base/widechar_width/libwidechar_width.a  /usr/lib64/libdouble-conversion.so  contrib/dragonbox-cmake/libdragonbox_to_chars.a  /usr/lib64/libre2.so  contrib/libcpuid-cmake/libcpuid.a  contrib/croaring-cmake/libroaring.a  contrib/brotli-cmake/libbrotli.a  /usr/lib64/liblz4.so  contrib/poco-cmake/MongoDB/lib_poco_mongodb.a  src/Common/StringUtils/libstring_utils.a  base/mysqlxx/libmysqlxx.a  base/common/libcommon.a  contrib/cityhash102/libcityhash.a  contrib/poco-cmake/Net/SSL/lib_poco_net_ssl.a  contrib/poco-cmake/Net/lib_poco_net.a  contrib/poco-cmake/Crypto/lib_poco_crypto.a  -lcrypto  contrib/poco-cmake/Util/lib_poco_util.a  contrib/poco-cmake/JSON/lib_poco_json.a  contrib/poco-cmake/JSON/lib_poco_json_pdjson.a  contrib/poco-cmake/XML/lib_poco_xml.a  contrib/poco-cmake/XML/lib_poco_xml_expat.a  contrib/replxx-cmake/libreplxx.a  contrib/cctz-cmake/libcctz.a  -Wl,--whole-archive /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/build/contrib/cctz-cmake/libtzdata.a -Wl,--no-whole-archive  contrib/fmtlib-cmake/libfmt.a  /usr/lib64/libmysqlclient.so  /usr/lib64/libboost_system.so.1.77.0  /usr/lib64/libzstd.so  /usr/lib64/libicui18n.so  /usr/lib64/libicuuc.so  /usr/lib64/libicudata.so  /usr/lib64/libcapnpc.so  /usr/lib64/libcapnp.so  /usr/lib64/libkj.so  contrib/libhdfs3-cmake/libhdfs3.a  contrib/krb5-cmake/libkrb5.a  /usr/lib64/libgsasl.so  /usr/lib64/libxml2.so  /usr/lib64/libprotobuf.so  /usr/lib64/liblzma.so  contrib/amqpcpp-cmake/libamqp-cpp.a  -lssl  libcassandra_static.a  /usr/lib64/libssl.so  /usr/lib64/libcrypto.so  contrib/libuv/libuv_a.a  -lpthread  -ldl  -lrt  /usr/lib64/libboost_context.so.1.77.0  contrib/poco-cmake/Data/ODBC/lib_poco_data_odbc.a  contrib/poco-cmake/Data/lib_poco_data.a  contrib/poco-cmake/Foundation/lib_poco_foundation.a  /usr/lib64/libz.so  contrib/poco-cmake/Foundation/lib_poco_foundation_pcre.a  -Wl,--start-group  -l:libstdc++.a  -l:libstdc++fs.a  contrib/libunwind-cmake/libunwind.a  -Wl,--end-group  /usr/lib64/libodbc.so  /usr/lib64/libltdl.a  -nodefaultlibs -lgcc  -lc -lm -lrt -lpthread -ldl && :
[ 7546s] /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/src/Common/ThreadFuzzer.cpp:268: error: undefined reference to '__pthread_mutex_lock'
[ 7546s] /home/abuild/rpmbuild/BUILD/clickhouse-21.8.8.29/src/Common/ThreadFuzzer.cpp:268: error: undefined reference to '__pthread_mutex_unlock'
```

Unfortunately, glibc 2.34 dropped `__pthread_mutex_lock` and `__pthread_mutex_unlock` from the public interface: https://sourceware.org/git/?p=glibc.git;a=commit;h=8ec022a037788cc540c5670b0c9b1aa137bfbf97

Mind double underscore prefix, regular `pthread_mutex_lock` and `pthread_mutex_unlock` are still there, but the ThreadFuzzer relies on the underscored symbols.

### PR DESCRIPTION
**Pull request by alexey-milovidov**
Changelog category (leave one):
- Build/Testing/Packaging Improvement

Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Hermetic builds: use fixed version of libc and make sure that no source or binary files from the host OS are using during build. This closes #27133. This closes #21435. This closes #30462.

Detailed description / Documentation draft:
See also #24371 and #22113.

### CODE REVIEW

**Comment by pkit** [comment]
@alexey-milovidov 
Err, doesn't close #30462 at all.
Still fails to build on glibc 2.35
See #43633

**Comment by Algunenano** [comment]
> Still fails to build on glibc 2.35 using current master https://github.com/ClickHouse/ClickHouse/commit/6531ff765d0910f732b80a4a650f0644622306ad

Are you sure it's the same problem? The hermetic build works fine for me with an even newer glibc:
```
$ pacman -Q glibc
glibc 2.36-6
```

**Comment by alexey-milovidov** [comment]
We don't access the system's libc during build time. So, the build is hermetic in this regard.
But the built binary still has to access the target machine's libc library at runtime.
