### PR TITLE
Make a dangling DataPartsAnyLock token a compile-time error

### PR DESCRIPTION
**Pull request by groeneai**
Related: https://github.com/ClickHouse/ClickHouse/pull/120093

### Changelog category (leave one):
- Not for changelog (changelog entry is not required)

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):
Binding a `DataPartsAnyLock` token to a reference that outlives its parts lock is now a compile-time error. No user-visible change.

### Description

`DataPartsAnyLock` (`src/Storages/MergeTree/MergeTreeData.h`) is the token that 14 `MergeTreeData` members accept as the caller's proof that it holds `data_parts_mutex`. Its two converting constructors take the lock by `const &`, so the token's lifetime was not tied to the lock's, and this compiled silently:

```cpp
const DB::DataPartsAnyLock & token = data.readLockParts();
```

Guaranteed elision materialises the token directly and extends it to the end of the enclosing block, while the `DataPartsSharedLock` it was built from is destroyed at the semicolon. The token then certifies a lock that no longer exists.

`[[clang::lifetimebound]]` on each constructor parameter turns that spelling into:

```
error: temporary bound to local reference 'token' will be destroyed at the end of the full-expression [-Werror,-Wdangling]
```

The token now also keeps the address of the lock it was built from. Emscripten's clang 24, which the `wasm64` build uses, verifies such an annotation instead of trusting it, and rejects it while the token stores nothing. The pointer is never dereferenced, so the token still carries no runtime meaning.

I measured both directions under clang-21, under the CI-pinned clang-22, and under clang 24 in the container the `wasm64` job uses: the spelling above is clean without the attribute and an error with it, a full build is clean, and the 24 `src/` translation units that can construct a token are clean.

Nothing else needed changing: every mention of the type outside its own definition is a `const DataPartsAnyLock &` parameter, so a conversion can only happen in call-argument position, where the token and the lock are destroyed together.

@ azat asked for this in https://github.com/ClickHouse/ClickHouse/pull/120093#issuecomment-5759888937:

> clang::lifetimebound make sense, please open PR and assign me

No test is added: the only effect is a compiler diagnostic, and the tree has no negative-compile harness to run one in.

---
Workflow [[PR](https://s3.amazonaws.com/clickhouse-test-reports/praktika.html?PR=121376&sha=latest&name_0=PR)]
Sync PR [[sync-upstream/pr/121376](https://github.com/search?q=head%3Async-upstream%2Fpr%2F121376+org%3AClickHouse+type%3Apr&type=pullrequests)]

### Version info
- Merged into: `26.10.1.432` (included in `26.10` and later)

### CODE REVIEW

**Comment by groeneai** [comment]
<details>
<summary><b>Internal second-model review: adjudication log</b> (click to expand)</summary>

Pre-publication review by an independent model (engine: codex; 0 findings), plus my own cold review
of the resulting header: no blockers, no majors, 3 nits.

| # | Sev | Finding | Verdict | Evidence / action |
|---|-----|---------|---------|---|
| 1 | 💡 | The measurement sentence let "clang-21 and clang-22" distribute over the full-build clause, but the full build ran under clang-21 only | AGREE | Reworded before publication: the full build is attributed to clang-21, the 24 translation units to both compilers |
| 2 | 💡 | No code comment states the invariant the attribute encodes, and the class stores nothing, so a later reader could take the attribute for a no-op | DISAGREE | The explanation lands in the commit message instead, which states the invariant, the elision mechanism and the leading-position constraint in full. Not raised as follow-up work either: there is no user-reachable consequence |
| 3 | 💡 | No test pins the new contract | DISAGREE | Not constructible: the contract is a compiler diagnostic, there is no negative-compile harness in `ci/` or `tests/`, `CMakeLists.txt:169` blocks build-time `try_compile`, and stateless tests run against a server binary with no compiler present. Stated in the description instead |

Severity: ❌ blocker / ⚠️ major / 💡 nit. DISAGREE verdicts carry recorded evidence and are terminal
per finding.

One addition to the description's reasoning: I re-ran the "no existing site has the dangling shape"
closure against current `master` as well as this branch, and it is a plain text census, so it also
covers the release-only and sanitizer-only blocks that a debug build never compiles.

</details>

Session id: cron:clickhouse-review-slot-11:20260921-142100

**Review by azat — APPROVED** [review]

**Comment by groeneai** [comment]
`Build (wasm64)` went red on this branch and it was my diff. That job compiles with Emscripten 6.0.5, whose clang is 24.0.0git, and its lifetime-safety analysis verifies `[[clang::lifetimebound]]` instead of trusting it. With the token storing nothing there was nothing for it to verify:

```
src/Storages/MergeTree/MergeTreeData.h:153:24: error: could not verify that the return value can be lifetime bound to an unnamed parameter [-Werror,-Wlifetime-safety-lifetimebound-violation]
```

b3d1cd9 keeps the address of the lock the token was built from, which makes the annotation checkable. The pointer is never dereferenced, so the token still has no runtime meaning, and the check you approved is unchanged: the dangling spelling is still rejected, now by `-Wdangling` and also by `-Wlifetime-safety-use-after-scope`. Measured in the container that job uses: the three objects it failed on build clean, all 24 token-constructing translation units are clean, and the previous shape still fails the same three objects.

The alternative was to suppress `-Wlifetime-safety-lifetimebound-violation` in `cmake/warnings.cmake`, next to the four lifetime-safety diagnostics already disabled there for clang 23 and newer. That is green as well and I can switch to it if you prefer, but it would hide the same mistake in any future annotation.

**Comment by groeneai** [comment]
### CI finish ledger - b3d1cd9dbc38cdb97311e6830e3e8325090d71eb

Every failure below has an owner: a fixing PR (mine or external), or a full-effort fix task whose fixing-PR link will be posted here when it opens. Only `CH Inc sync` is exempt.

| Check / test | Reason | Owner / fixing PR |
|---|---|---|
| Upgrade check (amd_release) / Error message in clickhouse-server.log (see upgrade_error_messages.txt) | false red, not from this diff: the pre-upgrade phase runs the PREVIOUS release's suite, and v26.9's own `05211_backup_log_zero_byte_data_file` creates Log-family tables typed `AggregateFunction(countResample(10, 5, 1), UInt64, UInt64)`. `--upgrade-check` implies `--fake-drop`, so those tables outlive the restart and the new binary correctly refuses the empty-range parameterisation, giving `Code: 69 ARGUMENT_OUT_OF_BOUND` in `AsyncLoader::worker` once per leftover table | a fix task is created (investigating at full effort, fixing-PR link to follow on this PR) |
| Upgrade check (amd_release) / The mutation submitted before the upgrade was not finished by the new server (see mutation_across_upgrade.txt) | one and the same cause: `StorageSystemMutations::fillData` iterates databases with `skip_not_loaded = false`, so it waits on the failed table load and rethrows, and the runner's `system.mutations` probe returns empty instead of `1`. `mutation_across_upgrade.txt` is itself empty in this run | a fix task is created (investigating at full effort, fixing-PR link to follow on this PR) |

`Mergeable Check` and `PR` are the praktika aggregators reflecting that single `Upgrade check (amd_release)` red, not independent failures, so they are resolved by the rows above. `CH Inc sync` passed on this head.

This PR changes one header, `src/Storages/MergeTree/MergeTreeData.h`, and touches nothing aggregate-function or upgrade related. All 27 `Build (*)` legs are green on this head, `Build (wasm64)` included, so the compile-time property this change exists for holds on every flavour.

Session id: cron:our-pr-ci-monitor:20260922-030126

**Comment by groeneai** [comment]
Fixing PR for both `Upgrade check (amd_release)` rows here is open: #121484.

The previous release's own `05211_backup_log_zero_byte_data_file` types five Log family tables with `countResample(10, 5, 1)` and restores a copy of each. `--upgrade-check` implies `--fake-drop`, so they survive into the upgrade restart, where the new server refuses each one (#119728, an approved backward incompatible change) and logs the `<Error>`. The same failed load is what empties `mutation_across_upgrade.txt`: `system.mutations` iterates every database at `skip_not_loaded = false`, so `waitLoad` rethrows and the runner's probe reads nothing.
