### PR TITLE
Aggregate single-dictionary `LowCardinality` keys by index

### PR DESCRIPTION
**Pull request by bobrik**
This is perhaps a simpler/better alternative to #114993. I'm reusing the first benchmark commit from there. Notice that it does not depend on #114982 to speed up aggregations of wide integers.

When a `MergeTree` part has one verified `LowCardinality` dictionary, its indexes uniquely identify values throughout the part. Use these indexes directly as aggregation keys and retain the dictionary for result finalization.

Merge parallel aggregation states directly when they share the same dictionary. Normalize back to value-based aggregation when the dictionary changes.

This gives a very nice speedup to the benchmark in the previous commit:

| Width           | LC before | LC after | Change |
|-----------------|----------:|---------:|-------:|
| `UInt8`         |  0.1209 s | 0.1212 s |  +0.3% |
| `UInt16`        |  0.1697 s | 0.1710 s |  +0.7% |
| `UInt32`        |  0.1896 s | 0.1475 s | -22.2% |
| `UInt64`        |  0.1977 s | 0.1459 s | -26.2% |
| `UInt128`       |  0.5752 s | 0.1520 s | -73.6% |
| `UInt256`       |  0.9080 s | 0.1603 s | -82.3% |
| `String` (6 B)  |  0.2532 s | 0.1466 s | -42.1% |
| `String` (26 B) |  0.2489 s | 0.1474 s | -40.8% |
| `String` (56 B) |  0.2609 s | 0.1501 s | -42.5% |

### Changelog category (leave one):
- Performance Improvement

### Changelog entry (a [user-readable short description](https://github.com/ClickHouse/ClickHouse/blob/master/docs/changelog_entry_guidelines.md) of the changes that goes into CHANGELOG.md):

Speed up single dictionary `LowCardinality` aggregations by aggregating keys by dictionary index.

---
Workflow [[PR](https://s3.amazonaws.com/clickhouse-test-reports/json.html?PR=115925&sha=latest&name_0=PR)]
Sync PR [[sync-upstream/pr/115925](https://github.com/search?q=head%3Async-upstream%2Fpr%2F115925+org%3AClickHouse+type%3Apr&type=pullrequests)]

### CODE REVIEW

**Comment by bobrik** [comment]
Rebased to resolve the trivial include conflicts with #116267.

**Comment by bobrik** [comment]
While the conflicts were minimal, #96630 did change the code to cause compilation errors after the rebase.

I adjusted the code to work with the new topk optimization. cc @thevar1able

**Comment by bobrik** [comment]
I added specialization to squeeze a bit more out of it based on benchmarks on bigger data:

image

**Comment by bobrik** [comment]
### Table schema

<details>
  <summary>CREATE TABLE profiles_v4_replica ...</summary>

```sql
CREATE TABLE profiles_v4_replica
(
    `timestamp` DateTime CODEC(DoubleDelta, ZSTD(1)),
    `duration` UInt32 CODEC(T64, ZSTD(1)),
    `profileType` LowCardinality(String) CODEC(ZSTD(1)),
    `serviceName` LowCardinality(String) CODEC(ZSTD(1)),
    `label_build_id` LowCardinality(String) CODEC(ZSTD(1)),
    `label_colo_allegiance` LowCardinality(String) CODEC(ZSTD(1)),
    `label_app_name` LowCardinality(String) CODEC(ZSTD(1)),
    `label_colo_name` LowCardinality(String) CODEC(ZSTD(1)),
    `label_colo_owner` LowCardinality(String) CODEC(ZSTD(1)),
    `label_colo_region` LowCardinality(String) CODEC(ZSTD(1)),
    `label_cpu_arch` LowCardinality(String) CODEC(ZSTD(1)),
    `label_debian_release` LowCardinality(String) CODEC(ZSTD(1)),
    `label_edge_reboot_release` LowCardinality(String) CODEC(ZSTD(1)),
    `label_environment` LowCardinality(String) CODEC(ZSTD(1)),
    `label_exe` LowCardinality(String) CODEC(ZSTD(1)),
    `label_hardware_generation` LowCardinality(String) CODEC(ZSTD(1)),
    `label_instance` LowCardinality(String) CODEC(ZSTD(1)),
    `label_kernel_release` LowCardinality(String) CODEC(ZSTD(1)),
    `label_kubernetes_cluster` LowCardinality(String) CODEC(ZSTD(1)),
    `label_kubernetes_container_name` LowCardinality(String) CODEC(ZSTD(1)),
    `label_kubernetes_namespace` LowCardinality(String) CODEC(ZSTD(1)),
    `label_kubernetes_pod_name` LowCardinality(String) CODEC(ZSTD(1)),
    `label_node_status` LowCardinality(String) CODEC(ZSTD(1)),
    `label_node_type` LowCardinality(String) CODEC(ZSTD(1)),
    `label_package_version` LowCardinality(String) CODEC(ZSTD(1)),
    `label_pop_name` LowCardinality(String) CODEC(ZSTD(1)),
    `label_sliver` LowCardinality(String) CODEC(ZSTD(1)),
    `label_tier` LowCardinality(String) CODEC(ZSTD(1)),
    `sumOfValues` UInt64 CODEC(T64, ZSTD(1)),
    `profile` String CODEC(ZSTD(3)),
    `stackMap.stack` Array(LowCardinality(UInt128)),
    `stackMap.value` Array(UInt64)
)
ENGINE = MergeTree
PARTITION BY toDate(timestamp)
ORDER BY (serviceName, profileType, label_app_name, label_instance, timestamp)
SETTINGS index_granularity = 8192
```
</details>

There are:

* 190,244,623 plain rows
* 15,144,156,707 rows after `ARRAY JOIN stackMap`.

These are the parts and their sizes (in MiB):

```
$ du -ms ~/clickhouse/data/default/profiles_v4_replica/*
35370   /home/ivan/clickhouse/data/default/profiles_v4_replica/20260818_1_1_0
34312   /home/ivan/clickhouse/data/default/profiles_v4_replica/20260818_2_2_0
123     /home/ivan/clickhouse/data/default/profiles_v4_replica/20260818_3_3_0
109     /home/ivan/clickhouse/data/default/profiles_v4_replica/20260818_4_4_0
37      /home/ivan/clickhouse/data/default/profiles_v4_replica/20260818_5_5_0
26      /home/ivan/clickhouse/data/default/profiles_v4_replica/20260818_6_6_0
14      /home/ivan/clickhouse/data/default/profiles_v4_replica/20260818_7_7_0
5       /home/ivan/clickhouse/data/default/profiles_v4_replica/20260818_8_8_0
1       /home/ivan/clickhouse/data/default/profiles_v4_replica/20260818_9_9_0
0       /home/ivan/clickhouse/data/default/profiles_v4_replica/detached
1       /home/ivan/clickhouse/data/default/profiles_v4_replica/format_version.txt
```

### Queries

### Aggregate by an `Array(LowCardinality(UInt128))` column

#### 1 thread


```sql
SELECT count()
FROM
(
    SELECT
        stackMap.stack AS stack,
        sum(stackMap.value) AS value
    FROM profiles_v4_replica
    ARRAY JOIN stackMap
    WHERE (profileType = 'process_cpu:cpu:nanoseconds:cpu:nanoseconds') AND (serviceName = 'ebpf.profiler') AND (label_app_name = 'fl2.service') AND (timestamp >= '2026-08-18 00:00:00') AND (timestamp < '2026-08-19 00:00:00')
    GROUP BY stack
    ORDER BY value ASC
)
SETTINGS max_threads = 1
```

* Baseline:

```
ivan@36com1306:~/projects/clickhouse/build$ ../bench.py --clickhouse=/tmp/clickhouse-9d8eed34c114 --path=$HOME/clickhouse --runs=3 --query="SELECT count() FROM ( SELECT stackMap.stack AS stack, sum(stackMap.value) AS value FROM profiles_v4_replica ARRAY JOIN stackMap WHERE profileType = 'process_cpu:cpu:nanoseconds:cpu:nanoseconds' AND serviceName = 'ebpf.profiler' AND label_app_name = 'fl2.service' AND timestamp >= '2026-08-18 00:00:00' and timestamp < '2026-08-19 00:00:00' GROUP BY stack ORDER BY value ASC) SETTINGS max_threads = 1"
wall: 209.95s, cpu: 209.88s, memory:   4.57GiB
wall: 208.42s, cpu: 208.35s, memory:   4.57GiB
wall: 210.03s, cpu: 209.97s, memory:   4.57GiB
```

* Patched:

```
ivan@36com1306:~/projects/clickhouse/build$ ../bench.py --clickhouse=/tmp/clickhouse-bd53f1a23f7d --path=$HOME/clickhouse --runs=3 --query="SELECT count() FROM ( SELECT stackMap.stack AS stack, sum(stackMap.value) AS value FROM profiles_v4_replica ARRAY JOIN stackMap WHERE profileType = 'process_cpu:cpu:nanoseconds:cpu:nanoseconds' AND serviceName = 'ebpf.profiler' AND label_app_name = 'fl2.service' AND timestamp >= '2026-08-18 00:00:00' and timestamp < '2026-08-19 00:00:00' GROUP BY stack ORDER BY value ASC) SETTINGS max_threads = 1"
wall: 151.70s, cpu: 151.64s, memory:   4.57GiB
wall: 150.55s, cpu: 150.50s, memory:   4.57GiB
wall: 150.60s, cpu: 150.54s, memory:   4.57GiB
```

The speedup here is not as good as I would like because one reader reads multiple parts, which means that is sees multiple dictionaries, which in turn means falling back to the previous aggregation path that is more expensive. Keeping the optimization going is probably feasible, but it would make this PR even bigger, so I'm not sure if it's a good idea (it's already quite big). It would be a nice win though. The current results show us doing the fast path only on the first part with about half of the data.

#### 64 threads, default parallelism

```sql
SELECT count()
FROM
(
    SELECT
        stackMap.stack AS stack,
        sum(stackMap.value) AS value
    FROM profiles_v4_replica
    ARRAY JOIN stackMap
    WHERE (profileType = 'process_cpu:cpu:nanoseconds:cpu:nanoseconds') AND (serviceName = 'ebpf.profiler') AND (label_app_name = 'fl2.service') AND (timestamp >= '2026-08-18 00:00:00') AND (timestamp < '2026-08-19 00:00:00')
    GROUP BY stack
    ORDER BY value ASC
)
SETTINGS max_threads = 64
```

* Baseline:

```
$ ../bench.py --clickhouse=/tmp/clickhouse-9d8eed34c114 --path=$HOME/clickhouse --runs=3 --query="SELECT count() FROM ( SELECT stackMap.stack AS stack, sum(stackMap.value) AS value FROM profiles_v4_replica ARRAY JOIN stackMap WHERE profileType = 'process_cpu:cpu:nanoseconds:cpu:nanoseconds' AND serviceName = 'ebpf.profiler' AND label_app_name = 'fl2.service' AND timestamp >= '2026-08-18 00:00:00' and timestamp < '2026-08-19 00:00:00' GROUP BY stack ORDER BY value ASC) SETTINGS max_threads = 64"
wall:  51.90s, cpu: 279.78s, memory:   9.27GiB
wall:  51.38s, cpu: 275.69s, memory:   9.76GiB
wall:  51.95s, cpu: 280.98s, memory:   9.28GiB
```

image

* Patched:

```
ivan@36com1306:~/projects/clickhouse/build$ ../bench.py --clickhouse=/tmp/clickhouse-bd53f1a23f7d --path=$HOME/clickhouse --runs=3 --query="SELECT count() FROM ( SELECT stackMap.stack AS stack, sum(stackMap.value) AS value FROM profiles_v4_replica ARRAY JOIN stackMap WHERE profileType = 'process_cpu:cpu:nanoseconds:cpu:nanoseconds' AND serviceName = 'ebpf.profiler' AND label_app_name = 'fl2.service' AND timestamp >= '2026-08-18 00:00:00' and timestamp < '2026-08-19 00:00:00' GROUP BY stack ORDER BY value ASC) SETTINGS max_threads = 64"
wall:  20.03s, cpu:  97.93s, memory:   9.02GiB
wall:  20.41s, cpu:  99.08s, memory:   9.08GiB
wall:  21.08s, cpu: 100.96s, memory:   9.10GiB
```

**-60% wall time, -64% CPU time!** Same memory usage. Pretty good.

image

#### 64 threads, more parallelism

```sql
SELECT count()
FROM
(
    SELECT
        stackMap.stack AS stack,
        sum(stackMap.value) AS value
    FROM profiles_v4_replica
    ARRAY JOIN stackMap
    WHERE (profileType = 'process_cpu:cpu:nanoseconds:cpu:nanoseconds') AND (serviceName = 'ebpf.profiler') AND (label_app_name = 'fl2.service') AND (timestamp >= '2026-08-18 00:00:00') AND (timestamp < '2026-08-19 00:00:00')
    GROUP BY stack
    ORDER BY value ASC
)
SETTINGS max_threads = 64, merge_tree_min_rows_for_concurrent_read = 1, merge_tree_min_bytes_for_concurrent_read = 0, merge_tree_min_read_task_size = 1, merge_tree_min_bytes_per_read_stream = 0
```

* Baseline:

```
$ ../bench.py --clickhouse=/tmp/clickhouse-9d8eed34c114 --path=$HOME/clickhouse --runs=3 --query="SELECT count() FROM ( SELECT stackMap.stack AS stack, sum(stackMap.value) AS value FROM profiles_v4_replica ARRAY JOIN stackMap WHERE profileType = 'process_cpu:cpu:nanoseconds:cpu:nanoseconds' AND serviceName = 'ebpf.profiler' AND label_app_name = 'fl2.service' AND timestamp >= '2026-08-18 00:00:00' and timestamp < '2026-08-19 00:00:00' GROUP BY stack ORDER BY value ASC) SETTINGS max_threads = 64, merge_tree_min_rows_for_concurrent_read = 1, merge_tree_min_bytes_for_concurrent_read = 0, merge_tree_min_read_task_size = 1, merge_tree_min_bytes_per_read_stream = 0"
wall:   8.48s, cpu: 490.35s, memory:  39.96GiB
wall:   8.56s, cpu: 484.85s, memory:  40.79GiB
wall:   8.41s, cpu: 483.84s, memory:  40.40GiB
```

* Patched:

```
ivan@36com1306:~/projects/clickhouse/build$ ../bench.py --clickhouse=/tmp/clickhouse-bd53f1a23f7d --path=$HOME/clickhouse --runs=3 --query="SELECT count() FROM ( SELECT stackMap.stack AS stack, sum(stackMap.value) AS value FROM profiles_v4_replica ARRAY JOIN stackMap WHERE profileType = 'process_cpu:cpu:nanoseconds:cpu:nanoseconds' AND serviceName = 'ebpf.profiler' AND label_app_name = 'fl2.service' AND timestamp >= '2026-08-18 00:00:00' and timestamp < '2026-08-19 00:00:00' GROUP BY stack ORDER BY value ASC) SETTINGS max_threads = 64, merge_tree_min_rows_for_concurrent_read = 1, merge_tree_min_bytes_for_concurrent_read = 0, merge_tree_min_read_task_size = 1, merge_tree_min_bytes_per_read_stream = 0"
wall:   8.61s, cpu: 488.46s, memory:  40.26GiB
wall:   8.40s, cpu: 486.40s, memory:  41.24GiB
wall:   8.62s, cpu: 496.56s, memory:  40.52GiB
```

It seems that task stealing disengages the optimization due to dictionary changes here too.

**Comment by bobrik** [comment]
Single thread north star:

```
wall:  78.81s, cpu:  78.74s, memory:   4.53GiB
wall:  78.70s, cpu:  78.65s, memory:   4.53GiB
wall:  78.14s, cpu:  78.10s, memory:   4.53GiB
```

That's -62% from the baseline. I'm trying to figure out how to not mess up parallel queries while doing this.

**Comment by bobrik** [comment]
I added a commit to preserve indexing across dictionary switches without compromising CPU or memory costs.

* Wall time:

| Configuration                   | Baseline | Before | Before vs baseline | After | After vs before | After vs baseline |
|---------------------------------|---------:|-------:|-------------------:|------:|----------------:|------------------:|
| 1 thread                        | 210.0s   | 150.6s |             -28.3% | 78.6s |          -47.8% |            -62.6% |
| 64 threads                      | 51.9s    | 20.4s  |             -60.7% | 17.4s |          -14.6% |            -66.4% |
| 64 threads, smallest read tasks | 8.5s     | 8.6s   |              +1.5% | 8.1s  |           -5.7% |             -4.2% |

* CPU time:

| Configuration                   | Baseline | Before | Before vs baseline | After  | After vs before | After vs baseline |
|---------------------------------|---------:|-------:|-------------------:|-------:|----------------:|------------------:|
| 1 thread                        | 209.9s   | 150.5s |             -28.3% | 78.6s  |          -47.8% |            -62.6% |
| 64 threads                      | 279.8s   | 99.1s  |             -64.6% | 100.3s |           +1.2% |            -64.2% |
| 64 threads, smallest read tasks | 484.9s   | 488.5s |              +0.7% | 358.0s |          -26.7% |            -26.2% |

* Peak memory:

| Configuration                   | Baseline | Before   | Before vs baseline | After    | After vs before | After vs baseline |
|---------------------------------|---------:|---------:|-------------------:|---------:|----------------:|------------------:|
| 1 thread                        | 4.57 GiB | 4.57 GiB |               0.0% | 4.53 GiB |           -0.9% |             -0.9% |
| 64 threads                      | 9.28 GiB | 9.08 GiB |              -2.2% | 8.97 GiB |           -1.2% |             -3.3% |
| 64 threads, smallest read tasks | 40.4 GiB | 40.5 GiB |              +0.3% | 35.3 GiB |          -12.8% |            -12.6% |

No impact to numbers in the description as those exercise one part to begin with.

**Comment by bobrik** [comment]
I added another commit to optimize further by merging intermediates by index too (when possible).

* 1 thread (baseline: `wall: 209.91s, cpu: 209.84s, memory:   4.57GiB`):

```
wall:  78.15s, cpu:  78.11s, memory:   4.53GiB
wall:  78.43s, cpu:  78.39s, memory:   4.53GiB
wall:  78.84s, cpu:  78.80s, memory:   4.53GiB
```

* 64 threads (baseline: `wall:  51.18s, cpu: 277.04s, memory:   9.27GiB`):

```
wall:  15.75s, cpu:  97.53s, memory:   9.12GiB
wall:  15.63s, cpu:  98.22s, memory:   8.86GiB
wall:  16.57s, cpu: 100.81s, memory:   8.48GiB
```

* 64 threads, smallest read tasks (baseline: `wall:   8.52s, cpu: 485.62s, memory:  40.53GiB`):

```
wall:   7.76s, cpu: 377.62s, memory:  35.43GiB
wall:   7.69s, cpu: 377.70s, memory:  35.10GiB
wall:   7.43s, cpu: 362.83s, memory:  35.57GiB
```

Single thread is neutral (as expected), many threads are faster.

**Comment by bobrik** [comment]
I pushed another commit to optimize the smallest tasks case:

| Read settings | Metric | Before   | After    | Change |
|---------------|--------|---------:|---------:|-------:|
| Default       | Wall   |   16.0 s |   15.6 s |  -2.3% |
| Default       | CPU    |   98.9 s |   97.6 s |  -1.2% |
| Default       | Memory |  8.8 GiB |  9.0 GiB |  +2.5% |
| Small tasks   | Wall   |    7.5 s |    6.3 s | -15.9% |
| Small tasks   | CPU    |  361.0 s |  298.2 s | -17.4% |
| Small tasks   | Memory | 35.3 GiB | 34.9 GiB |  -1.2% |

**Comment by bobrik** [comment]
I updated the latest commit to speed it up some more (`Before` is the same, compare `After` to the comment above):

| Read settings | Metric | Before   | After    | Change |
|---------------|--------|---------:|---------:|-------:|
| Small tasks   | Wall   |    7.5 s |    6.1 s | -19.2% |
| Small tasks   | CPU    |  361.0 s |  270.9 s | -25.0% |
| Small tasks   | Memory | 35.3 GiB | 35.2 GiB |  -0.2% |

I also ran the whole thing through a few rounds of review and found a bunch of correctness issues, which are now fixed. 

One of the findings is that `groupArrayInsertAt`, `stochasticLinearRegression` and `stochasticLogisticRegression` are  order-dependent, but was not marked as such. These can probably be split into a separate PR.

I did not get any review flags from 5 runs in a row before pushing the latest version.

The diff size is now eye-watering, but most of it is in tests and a lot of it is to support testing of correctness.

**Comment by bobrik** [comment]
The CI is having hard time completing some tests in time even after I trimmed them down a bit.

I opened #118386 to fix a problem of slow `clickhouse-client` startup, which might be helpful here.

**Comment by bobrik** [comment]
I found the problem with slow tests: I was setting `max_block_size=1` to test my thing, but then carrying it over to query log scanning, which would go over all of the preceding queries in the run. It's fixed now, plus I added a commit to amend the review skill to spot these problems. Here it is split off into a separate PR: #119141.

The other two failures are known: #111892 + #118499.
