### PR TITLE
Fix incorrect postgresql query which fetches tables list

### LINKED ISSUE #33502: Does postgres engine support foreign wrappers?
I'm using https://clickhouse.com/docs/en/engines/database-engines/postgresql/ to connect into a pg db that has a foreign schema wrapper.  
https://www.postgresql.org/docs/current/postgres-fdw.html

Is foreign wrapper supported by clickhouse? I'm able to create a database `CREATE DATABASE a ENGINE = PostgreSQL` but there are no tables.

```sql
CREATE DATABASE pg_old
ENGINE = PostgreSQL('pg:5432', 'db', 'clickhouse', 'pwd', `foreign_schema`); -- connection is ok, no tables fetched by clickhouse
CREATE DATABASE pg_public
ENGINE = PostgreSQL('pg:5432', 'db', 'clickhouse', 'pwd', `public`); -- this one works, tables present, selects can be done etc.
```

### PR DESCRIPTION
**Pull request by kssenii**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix incorrect fetch postgresql tables query fro PostgreSQL database engine. Closes https://github.com/ClickHouse/ClickHouse/issues/33502.

### CODE REVIEW

**Comment by kssenii** [comment]
> ClickHouse special build check (actions) — 6/7 artifact groups are OK

was broken in master (fixed in https://github.com/ClickHouse/ClickHouse/pull/39288)

```
Jul 16 12:21:10 /build/build_docker/../src/Storages/MergeTree/MergedColumnOnlyOutputStream.cpp:42:9: error: passing result of std::move() as a const reference argument; no move will actually happen [performance-move-const-arg,-warnings-as-errors]
Jul 16 12:21:10         std::move(writer_settings),
Jul 16 12:21:10         ^~~~~~~~~~               ~
Jul 16 12:21:10 204305 warnings generated.
```
